// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: contract.sql

package sqlcgen

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const deleteContract = `-- name: DeleteContract :exec
DELETE FROM service_contracts WHERE id = $1
`

func (q *Queries) DeleteContract(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteContract, id)
	return err
}

const getContractByID = `-- name: GetContractByID :one
SELECT id, provider_id, shipper_id, status, valid_from, valid_to, created_at, updated_at FROM service_contracts WHERE id = $1
`

func (q *Queries) GetContractByID(ctx context.Context, id uuid.UUID) (ServiceContract, error) {
	row := q.db.QueryRow(ctx, getContractByID, id)
	var i ServiceContract
	err := row.Scan(
		&i.ID,
		&i.ProviderID,
		&i.ShipperID,
		&i.Status,
		&i.ValidFrom,
		&i.ValidTo,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const insertContract = `-- name: InsertContract :exec
INSERT INTO service_contracts (id, provider_id, shipper_id, status, valid_from, valid_to, created_at, updated_at)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
`

type InsertContractParams struct {
	ID         uuid.UUID          `db:"id" json:"id"`
	ProviderID uuid.UUID          `db:"provider_id" json:"provider_id"`
	ShipperID  uuid.UUID          `db:"shipper_id" json:"shipper_id"`
	Status     ContractStatus     `db:"status" json:"status"`
	ValidFrom  pgtype.Timestamptz `db:"valid_from" json:"valid_from"`
	ValidTo    pgtype.Timestamptz `db:"valid_to" json:"valid_to"`
	CreatedAt  pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt  pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
}

func (q *Queries) InsertContract(ctx context.Context, arg InsertContractParams) error {
	_, err := q.db.Exec(ctx, insertContract,
		arg.ID,
		arg.ProviderID,
		arg.ShipperID,
		arg.Status,
		arg.ValidFrom,
		arg.ValidTo,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	return err
}

const listActiveContractsByProviderAndShipper = `-- name: ListActiveContractsByProviderAndShipper :many
SELECT id, provider_id, shipper_id, status, valid_from, valid_to, created_at, updated_at FROM service_contracts
WHERE provider_id = $1 AND shipper_id = $2 AND status = 'CONTRACTED'
  AND valid_from <= $3 AND valid_to >= $3
ORDER BY created_at DESC
`

type ListActiveContractsByProviderAndShipperParams struct {
	ProviderID uuid.UUID          `db:"provider_id" json:"provider_id"`
	ShipperID  uuid.UUID          `db:"shipper_id" json:"shipper_id"`
	ValidFrom  pgtype.Timestamptz `db:"valid_from" json:"valid_from"`
}

func (q *Queries) ListActiveContractsByProviderAndShipper(ctx context.Context, arg ListActiveContractsByProviderAndShipperParams) ([]ServiceContract, error) {
	rows, err := q.db.Query(ctx, listActiveContractsByProviderAndShipper, arg.ProviderID, arg.ShipperID, arg.ValidFrom)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ServiceContract
	for rows.Next() {
		var i ServiceContract
		if err := rows.Scan(
			&i.ID,
			&i.ProviderID,
			&i.ShipperID,
			&i.Status,
			&i.ValidFrom,
			&i.ValidTo,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listContractsByProviderAndShipper = `-- name: ListContractsByProviderAndShipper :many
SELECT id, provider_id, shipper_id, status, valid_from, valid_to, created_at, updated_at FROM service_contracts WHERE provider_id = $1 AND shipper_id = $2 ORDER BY created_at DESC
`

type ListContractsByProviderAndShipperParams struct {
	ProviderID uuid.UUID `db:"provider_id" json:"provider_id"`
	ShipperID  uuid.UUID `db:"shipper_id" json:"shipper_id"`
}

func (q *Queries) ListContractsByProviderAndShipper(ctx context.Context, arg ListContractsByProviderAndShipperParams) ([]ServiceContract, error) {
	rows, err := q.db.Query(ctx, listContractsByProviderAndShipper, arg.ProviderID, arg.ShipperID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ServiceContract
	for rows.Next() {
		var i ServiceContract
		if err := rows.Scan(
			&i.ID,
			&i.ProviderID,
			&i.ShipperID,
			&i.Status,
			&i.ValidFrom,
			&i.ValidTo,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listContractsByShipper = `-- name: ListContractsByShipper :many
SELECT id, provider_id, shipper_id, status, valid_from, valid_to, created_at, updated_at FROM service_contracts WHERE shipper_id = $1 ORDER BY created_at DESC
`

func (q *Queries) ListContractsByShipper(ctx context.Context, shipperID uuid.UUID) ([]ServiceContract, error) {
	rows, err := q.db.Query(ctx, listContractsByShipper, shipperID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ServiceContract
	for rows.Next() {
		var i ServiceContract
		if err := rows.Scan(
			&i.ID,
			&i.ProviderID,
			&i.ShipperID,
			&i.Status,
			&i.ValidFrom,
			&i.ValidTo,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDraftContractsByProviderAndShipper = `-- name: ListDraftContractsByProviderAndShipper :many
SELECT id, provider_id, shipper_id, status, valid_from, valid_to, created_at, updated_at FROM service_contracts
WHERE provider_id = $1 AND shipper_id = $2 AND status = 'DRAFT'
ORDER BY created_at DESC
`

type ListDraftContractsByProviderAndShipperParams struct {
	ProviderID uuid.UUID `db:"provider_id" json:"provider_id"`
	ShipperID  uuid.UUID `db:"shipper_id" json:"shipper_id"`
}

func (q *Queries) ListDraftContractsByProviderAndShipper(ctx context.Context, arg ListDraftContractsByProviderAndShipperParams) ([]ServiceContract, error) {
	rows, err := q.db.Query(ctx, listDraftContractsByProviderAndShipper, arg.ProviderID, arg.ShipperID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ServiceContract
	for rows.Next() {
		var i ServiceContract
		if err := rows.Scan(
			&i.ID,
			&i.ProviderID,
			&i.ShipperID,
			&i.Status,
			&i.ValidFrom,
			&i.ValidTo,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateContract = `-- name: UpdateContract :exec
UPDATE service_contracts
SET status = $2, valid_from = $3, valid_to = $4, updated_at = $5
WHERE id = $1
`

type UpdateContractParams struct {
	ID        uuid.UUID          `db:"id" json:"id"`
	Status    ContractStatus     `db:"status" json:"status"`
	ValidFrom pgtype.Timestamptz `db:"valid_from" json:"valid_from"`
	ValidTo   pgtype.Timestamptz `db:"valid_to" json:"valid_to"`
	UpdatedAt pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
}

func (q *Queries) UpdateContract(ctx context.Context, arg UpdateContractParams) error {
	_, err := q.db.Exec(ctx, updateContract,
		arg.ID,
		arg.Status,
		arg.ValidFrom,
		arg.ValidTo,
		arg.UpdatedAt,
	)
	return err
}
