// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: cost.sql

package sqlcgen

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
	"github.com/shopspring/decimal"
)

const deleteCostLineItemsByCategory = `-- name: DeleteCostLineItemsByCategory :exec
DELETE FROM shipment_cost_line_items WHERE shipment_id = $1 AND cost_category = $2
`

type DeleteCostLineItemsByCategoryParams struct {
	ShipmentID   uuid.UUID    `db:"shipment_id" json:"shipment_id"`
	CostCategory CostCategory `db:"cost_category" json:"cost_category"`
}

func (q *Queries) DeleteCostLineItemsByCategory(ctx context.Context, arg DeleteCostLineItemsByCategoryParams) error {
	_, err := q.db.Exec(ctx, deleteCostLineItemsByCategory, arg.ShipmentID, arg.CostCategory)
	return err
}

const getCostSummary = `-- name: GetCostSummary :one
SELECT id, shipment_id, cost_category, rate_id, invoice_id, invoice_no, provider_id, total_amount, total_currency, calculated_at, calculation_base FROM shipment_cost_summaries WHERE shipment_id = $1 AND cost_category = $2
`

type GetCostSummaryParams struct {
	ShipmentID   uuid.UUID    `db:"shipment_id" json:"shipment_id"`
	CostCategory CostCategory `db:"cost_category" json:"cost_category"`
}

func (q *Queries) GetCostSummary(ctx context.Context, arg GetCostSummaryParams) (ShipmentCostSummary, error) {
	row := q.db.QueryRow(ctx, getCostSummary, arg.ShipmentID, arg.CostCategory)
	var i ShipmentCostSummary
	err := row.Scan(
		&i.ID,
		&i.ShipmentID,
		&i.CostCategory,
		&i.RateID,
		&i.InvoiceID,
		&i.InvoiceNo,
		&i.ProviderID,
		&i.TotalAmount,
		&i.TotalCurrency,
		&i.CalculatedAt,
		&i.CalculationBase,
	)
	return i, err
}

const insertCostLineItem = `-- name: InsertCostLineItem :exec
INSERT INTO shipment_cost_line_items (
    id, shipment_id, cost_category, charge_code, charge_name, category,
    amount, currency, quantity, unit_price, unit_currency, applied_scope,
    remarks, segment_id, segment_index
) VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14, $15)
`

type InsertCostLineItemParams struct {
	ID           uuid.UUID       `db:"id" json:"id"`
	ShipmentID   uuid.UUID       `db:"shipment_id" json:"shipment_id"`
	CostCategory CostCategory    `db:"cost_category" json:"cost_category"`
	ChargeCode   string          `db:"charge_code" json:"charge_code"`
	ChargeName   pgtype.Text     `db:"charge_name" json:"charge_name"`
	Category     pgtype.Text     `db:"category" json:"category"`
	Amount       decimal.Decimal `db:"amount" json:"amount"`
	Currency     string          `db:"currency" json:"currency"`
	Quantity     pgtype.Numeric  `db:"quantity" json:"quantity"`
	UnitPrice    pgtype.Numeric  `db:"unit_price" json:"unit_price"`
	UnitCurrency pgtype.Text     `db:"unit_currency" json:"unit_currency"`
	AppliedScope pgtype.Text     `db:"applied_scope" json:"applied_scope"`
	Remarks      pgtype.Text     `db:"remarks" json:"remarks"`
	SegmentID    pgtype.UUID     `db:"segment_id" json:"segment_id"`
	SegmentIndex pgtype.Int4     `db:"segment_index" json:"segment_index"`
}

func (q *Queries) InsertCostLineItem(ctx context.Context, arg InsertCostLineItemParams) error {
	_, err := q.db.Exec(ctx, insertCostLineItem,
		arg.ID,
		arg.ShipmentID,
		arg.CostCategory,
		arg.ChargeCode,
		arg.ChargeName,
		arg.Category,
		arg.Amount,
		arg.Currency,
		arg.Quantity,
		arg.UnitPrice,
		arg.UnitCurrency,
		arg.AppliedScope,
		arg.Remarks,
		arg.SegmentID,
		arg.SegmentIndex,
	)
	return err
}

const listCostLineItemsByCategory = `-- name: ListCostLineItemsByCategory :many
SELECT id, shipment_id, cost_category, charge_code, charge_name, category, amount, currency, quantity, unit_price, unit_currency, applied_scope, remarks, segment_id, segment_index FROM shipment_cost_line_items WHERE shipment_id = $1 AND cost_category = $2
`

type ListCostLineItemsByCategoryParams struct {
	ShipmentID   uuid.UUID    `db:"shipment_id" json:"shipment_id"`
	CostCategory CostCategory `db:"cost_category" json:"cost_category"`
}

func (q *Queries) ListCostLineItemsByCategory(ctx context.Context, arg ListCostLineItemsByCategoryParams) ([]ShipmentCostLineItem, error) {
	rows, err := q.db.Query(ctx, listCostLineItemsByCategory, arg.ShipmentID, arg.CostCategory)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ShipmentCostLineItem
	for rows.Next() {
		var i ShipmentCostLineItem
		if err := rows.Scan(
			&i.ID,
			&i.ShipmentID,
			&i.CostCategory,
			&i.ChargeCode,
			&i.ChargeName,
			&i.Category,
			&i.Amount,
			&i.Currency,
			&i.Quantity,
			&i.UnitPrice,
			&i.UnitCurrency,
			&i.AppliedScope,
			&i.Remarks,
			&i.SegmentID,
			&i.SegmentIndex,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCostLineItemsByShipment = `-- name: ListCostLineItemsByShipment :many
SELECT id, shipment_id, cost_category, charge_code, charge_name, category, amount, currency, quantity, unit_price, unit_currency, applied_scope, remarks, segment_id, segment_index FROM shipment_cost_line_items WHERE shipment_id = $1 ORDER BY cost_category, charge_code
`

func (q *Queries) ListCostLineItemsByShipment(ctx context.Context, shipmentID uuid.UUID) ([]ShipmentCostLineItem, error) {
	rows, err := q.db.Query(ctx, listCostLineItemsByShipment, shipmentID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ShipmentCostLineItem
	for rows.Next() {
		var i ShipmentCostLineItem
		if err := rows.Scan(
			&i.ID,
			&i.ShipmentID,
			&i.CostCategory,
			&i.ChargeCode,
			&i.ChargeName,
			&i.Category,
			&i.Amount,
			&i.Currency,
			&i.Quantity,
			&i.UnitPrice,
			&i.UnitCurrency,
			&i.AppliedScope,
			&i.Remarks,
			&i.SegmentID,
			&i.SegmentIndex,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertCostSummary = `-- name: UpsertCostSummary :exec
INSERT INTO shipment_cost_summaries (
    id, shipment_id, cost_category, rate_id, invoice_id, invoice_no,
    provider_id, total_amount, total_currency, calculated_at, calculation_base
) VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11)
ON CONFLICT (shipment_id, cost_category)
DO UPDATE SET
    rate_id = EXCLUDED.rate_id,
    invoice_id = EXCLUDED.invoice_id,
    invoice_no = EXCLUDED.invoice_no,
    provider_id = EXCLUDED.provider_id,
    total_amount = EXCLUDED.total_amount,
    total_currency = EXCLUDED.total_currency,
    calculated_at = EXCLUDED.calculated_at,
    calculation_base = EXCLUDED.calculation_base
`

type UpsertCostSummaryParams struct {
	ID              uuid.UUID          `db:"id" json:"id"`
	ShipmentID      uuid.UUID          `db:"shipment_id" json:"shipment_id"`
	CostCategory    CostCategory       `db:"cost_category" json:"cost_category"`
	RateID          pgtype.UUID        `db:"rate_id" json:"rate_id"`
	InvoiceID       pgtype.UUID        `db:"invoice_id" json:"invoice_id"`
	InvoiceNo       pgtype.Text        `db:"invoice_no" json:"invoice_no"`
	ProviderID      pgtype.UUID        `db:"provider_id" json:"provider_id"`
	TotalAmount     decimal.Decimal    `db:"total_amount" json:"total_amount"`
	TotalCurrency   string             `db:"total_currency" json:"total_currency"`
	CalculatedAt    pgtype.Timestamptz `db:"calculated_at" json:"calculated_at"`
	CalculationBase pgtype.Text        `db:"calculation_base" json:"calculation_base"`
}

func (q *Queries) UpsertCostSummary(ctx context.Context, arg UpsertCostSummaryParams) error {
	_, err := q.db.Exec(ctx, upsertCostSummary,
		arg.ID,
		arg.ShipmentID,
		arg.CostCategory,
		arg.RateID,
		arg.InvoiceID,
		arg.InvoiceNo,
		arg.ProviderID,
		arg.TotalAmount,
		arg.TotalCurrency,
		arg.CalculatedAt,
		arg.CalculationBase,
	)
	return err
}
