// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: document.sql

package sqlcgen

import (
	"context"
	"encoding/json"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const getDocumentByID = `-- name: GetDocumentByID :one
SELECT id, shipment_id, doc_type, origin, file_name, mime_type, storage_uri, file_size, uploaded_by, status, version, metadata, content, created_at, updated_at FROM documents WHERE id = $1
`

func (q *Queries) GetDocumentByID(ctx context.Context, id uuid.UUID) (Document, error) {
	row := q.db.QueryRow(ctx, getDocumentByID, id)
	var i Document
	err := row.Scan(
		&i.ID,
		&i.ShipmentID,
		&i.DocType,
		&i.Origin,
		&i.FileName,
		&i.MimeType,
		&i.StorageUri,
		&i.FileSize,
		&i.UploadedBy,
		&i.Status,
		&i.Version,
		&i.Metadata,
		&i.Content,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const insertDocument = `-- name: InsertDocument :exec
INSERT INTO documents (
    id, shipment_id, doc_type, origin, file_name, mime_type,
    storage_uri, file_size, uploaded_by, status, version,
    metadata, content, created_at, updated_at
) VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14, $15)
`

type InsertDocumentParams struct {
	ID         uuid.UUID          `db:"id" json:"id"`
	ShipmentID uuid.UUID          `db:"shipment_id" json:"shipment_id"`
	DocType    string             `db:"doc_type" json:"doc_type"`
	Origin     DocumentOrigin     `db:"origin" json:"origin"`
	FileName   string             `db:"file_name" json:"file_name"`
	MimeType   pgtype.Text        `db:"mime_type" json:"mime_type"`
	StorageUri string             `db:"storage_uri" json:"storage_uri"`
	FileSize   int64              `db:"file_size" json:"file_size"`
	UploadedBy uuid.UUID          `db:"uploaded_by" json:"uploaded_by"`
	Status     DocumentStatus     `db:"status" json:"status"`
	Version    int32              `db:"version" json:"version"`
	Metadata   json.RawMessage    `db:"metadata" json:"metadata"`
	Content    []byte             `db:"content" json:"content"`
	CreatedAt  pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt  pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
}

func (q *Queries) InsertDocument(ctx context.Context, arg InsertDocumentParams) error {
	_, err := q.db.Exec(ctx, insertDocument,
		arg.ID,
		arg.ShipmentID,
		arg.DocType,
		arg.Origin,
		arg.FileName,
		arg.MimeType,
		arg.StorageUri,
		arg.FileSize,
		arg.UploadedBy,
		arg.Status,
		arg.Version,
		arg.Metadata,
		arg.Content,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	return err
}

const insertDocumentReview = `-- name: InsertDocumentReview :exec
INSERT INTO document_reviews (id, document_id, reviewer_id, reviewed_at, decision, comment, discrepancies)
VALUES ($1, $2, $3, $4, $5, $6, $7)
`

type InsertDocumentReviewParams struct {
	ID            uuid.UUID          `db:"id" json:"id"`
	DocumentID    uuid.UUID          `db:"document_id" json:"document_id"`
	ReviewerID    uuid.UUID          `db:"reviewer_id" json:"reviewer_id"`
	ReviewedAt    pgtype.Timestamptz `db:"reviewed_at" json:"reviewed_at"`
	Decision      string             `db:"decision" json:"decision"`
	Comment       pgtype.Text        `db:"comment" json:"comment"`
	Discrepancies json.RawMessage    `db:"discrepancies" json:"discrepancies"`
}

func (q *Queries) InsertDocumentReview(ctx context.Context, arg InsertDocumentReviewParams) error {
	_, err := q.db.Exec(ctx, insertDocumentReview,
		arg.ID,
		arg.DocumentID,
		arg.ReviewerID,
		arg.ReviewedAt,
		arg.Decision,
		arg.Comment,
		arg.Discrepancies,
	)
	return err
}

const listDocumentReviewsByDocumentID = `-- name: ListDocumentReviewsByDocumentID :many
SELECT id, document_id, reviewer_id, reviewed_at, decision, comment, discrepancies FROM document_reviews WHERE document_id = $1 ORDER BY reviewed_at
`

func (q *Queries) ListDocumentReviewsByDocumentID(ctx context.Context, documentID uuid.UUID) ([]DocumentReview, error) {
	rows, err := q.db.Query(ctx, listDocumentReviewsByDocumentID, documentID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []DocumentReview
	for rows.Next() {
		var i DocumentReview
		if err := rows.Scan(
			&i.ID,
			&i.DocumentID,
			&i.ReviewerID,
			&i.ReviewedAt,
			&i.Decision,
			&i.Comment,
			&i.Discrepancies,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDocumentsByShipmentID = `-- name: ListDocumentsByShipmentID :many
SELECT id, shipment_id, doc_type, origin, file_name, mime_type, storage_uri, file_size, uploaded_by, status, version, metadata, content, created_at, updated_at FROM documents WHERE shipment_id = $1 ORDER BY created_at
`

func (q *Queries) ListDocumentsByShipmentID(ctx context.Context, shipmentID uuid.UUID) ([]Document, error) {
	rows, err := q.db.Query(ctx, listDocumentsByShipmentID, shipmentID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Document
	for rows.Next() {
		var i Document
		if err := rows.Scan(
			&i.ID,
			&i.ShipmentID,
			&i.DocType,
			&i.Origin,
			&i.FileName,
			&i.MimeType,
			&i.StorageUri,
			&i.FileSize,
			&i.UploadedBy,
			&i.Status,
			&i.Version,
			&i.Metadata,
			&i.Content,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDocumentsByShipmentIDAndDocType = `-- name: ListDocumentsByShipmentIDAndDocType :many
SELECT id, shipment_id, doc_type, origin, file_name, mime_type, storage_uri, file_size, uploaded_by, status, version, metadata, content, created_at, updated_at FROM documents WHERE shipment_id = $1 AND doc_type = $2 ORDER BY version DESC
`

type ListDocumentsByShipmentIDAndDocTypeParams struct {
	ShipmentID uuid.UUID `db:"shipment_id" json:"shipment_id"`
	DocType    string    `db:"doc_type" json:"doc_type"`
}

func (q *Queries) ListDocumentsByShipmentIDAndDocType(ctx context.Context, arg ListDocumentsByShipmentIDAndDocTypeParams) ([]Document, error) {
	rows, err := q.db.Query(ctx, listDocumentsByShipmentIDAndDocType, arg.ShipmentID, arg.DocType)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Document
	for rows.Next() {
		var i Document
		if err := rows.Scan(
			&i.ID,
			&i.ShipmentID,
			&i.DocType,
			&i.Origin,
			&i.FileName,
			&i.MimeType,
			&i.StorageUri,
			&i.FileSize,
			&i.UploadedBy,
			&i.Status,
			&i.Version,
			&i.Metadata,
			&i.Content,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateDocument = `-- name: UpdateDocument :exec
UPDATE documents
SET status = $2, version = $3, metadata = $4, content = $5, updated_at = $6
WHERE id = $1
`

type UpdateDocumentParams struct {
	ID        uuid.UUID          `db:"id" json:"id"`
	Status    DocumentStatus     `db:"status" json:"status"`
	Version   int32              `db:"version" json:"version"`
	Metadata  json.RawMessage    `db:"metadata" json:"metadata"`
	Content   []byte             `db:"content" json:"content"`
	UpdatedAt pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
}

func (q *Queries) UpdateDocument(ctx context.Context, arg UpdateDocumentParams) error {
	_, err := q.db.Exec(ctx, updateDocument,
		arg.ID,
		arg.Status,
		arg.Version,
		arg.Metadata,
		arg.Content,
		arg.UpdatedAt,
	)
	return err
}
