// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: domain_event.sql

package sqlcgen

import (
	"context"
	"encoding/json"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const insertDomainEvent = `-- name: InsertDomainEvent :exec
INSERT INTO domain_events (id, event_type, aggregate_id, aggregate_type, payload, occurred_at, published, created_at)
VALUES ($1, $2, $3, $4, $5, $6, FALSE, NOW())
`

type InsertDomainEventParams struct {
	ID            uuid.UUID          `db:"id" json:"id"`
	EventType     string             `db:"event_type" json:"event_type"`
	AggregateID   uuid.UUID          `db:"aggregate_id" json:"aggregate_id"`
	AggregateType string             `db:"aggregate_type" json:"aggregate_type"`
	Payload       json.RawMessage    `db:"payload" json:"payload"`
	OccurredAt    pgtype.Timestamptz `db:"occurred_at" json:"occurred_at"`
}

func (q *Queries) InsertDomainEvent(ctx context.Context, arg InsertDomainEventParams) error {
	_, err := q.db.Exec(ctx, insertDomainEvent,
		arg.ID,
		arg.EventType,
		arg.AggregateID,
		arg.AggregateType,
		arg.Payload,
		arg.OccurredAt,
	)
	return err
}

const listEventsByAggregate = `-- name: ListEventsByAggregate :many
SELECT id, event_type, aggregate_id, aggregate_type, payload, occurred_at, published, published_at, created_at FROM domain_events WHERE aggregate_id = $1 AND aggregate_type = $2 ORDER BY occurred_at
`

type ListEventsByAggregateParams struct {
	AggregateID   uuid.UUID `db:"aggregate_id" json:"aggregate_id"`
	AggregateType string    `db:"aggregate_type" json:"aggregate_type"`
}

func (q *Queries) ListEventsByAggregate(ctx context.Context, arg ListEventsByAggregateParams) ([]DomainEvent, error) {
	rows, err := q.db.Query(ctx, listEventsByAggregate, arg.AggregateID, arg.AggregateType)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []DomainEvent
	for rows.Next() {
		var i DomainEvent
		if err := rows.Scan(
			&i.ID,
			&i.EventType,
			&i.AggregateID,
			&i.AggregateType,
			&i.Payload,
			&i.OccurredAt,
			&i.Published,
			&i.PublishedAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUnpublishedEvents = `-- name: ListUnpublishedEvents :many
SELECT id, event_type, aggregate_id, aggregate_type, payload, occurred_at, published, published_at, created_at FROM domain_events WHERE published = FALSE ORDER BY occurred_at LIMIT $1
`

func (q *Queries) ListUnpublishedEvents(ctx context.Context, limit int32) ([]DomainEvent, error) {
	rows, err := q.db.Query(ctx, listUnpublishedEvents, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []DomainEvent
	for rows.Next() {
		var i DomainEvent
		if err := rows.Scan(
			&i.ID,
			&i.EventType,
			&i.AggregateID,
			&i.AggregateType,
			&i.Payload,
			&i.OccurredAt,
			&i.Published,
			&i.PublishedAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markEventPublished = `-- name: MarkEventPublished :exec
UPDATE domain_events SET published = TRUE, published_at = NOW() WHERE id = $1
`

func (q *Queries) MarkEventPublished(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, markEventPublished, id)
	return err
}
