// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: lane.sql

package sqlcgen

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const getLaneByID = `-- name: GetLaneByID :one
SELECT id, origin_id, destination_id, mode, distance_km, created_at, updated_at FROM lanes WHERE id = $1
`

func (q *Queries) GetLaneByID(ctx context.Context, id uuid.UUID) (Lane, error) {
	row := q.db.QueryRow(ctx, getLaneByID, id)
	var i Lane
	err := row.Scan(
		&i.ID,
		&i.OriginID,
		&i.DestinationID,
		&i.Mode,
		&i.DistanceKm,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getLaneByOriginAndDestination = `-- name: GetLaneByOriginAndDestination :many
SELECT id, origin_id, destination_id, mode, distance_km, created_at, updated_at FROM lanes WHERE origin_id = $1 AND destination_id = $2
`

type GetLaneByOriginAndDestinationParams struct {
	OriginID      uuid.UUID `db:"origin_id" json:"origin_id"`
	DestinationID uuid.UUID `db:"destination_id" json:"destination_id"`
}

func (q *Queries) GetLaneByOriginAndDestination(ctx context.Context, arg GetLaneByOriginAndDestinationParams) ([]Lane, error) {
	rows, err := q.db.Query(ctx, getLaneByOriginAndDestination, arg.OriginID, arg.DestinationID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Lane
	for rows.Next() {
		var i Lane
		if err := rows.Scan(
			&i.ID,
			&i.OriginID,
			&i.DestinationID,
			&i.Mode,
			&i.DistanceKm,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const insertLane = `-- name: InsertLane :exec
INSERT INTO lanes (id, origin_id, destination_id, mode, distance_km, created_at, updated_at)
VALUES ($1, $2, $3, $4, $5, $6, $7)
`

type InsertLaneParams struct {
	ID            uuid.UUID          `db:"id" json:"id"`
	OriginID      uuid.UUID          `db:"origin_id" json:"origin_id"`
	DestinationID uuid.UUID          `db:"destination_id" json:"destination_id"`
	Mode          TransportMode      `db:"mode" json:"mode"`
	DistanceKm    pgtype.Numeric     `db:"distance_km" json:"distance_km"`
	CreatedAt     pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt     pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
}

func (q *Queries) InsertLane(ctx context.Context, arg InsertLaneParams) error {
	_, err := q.db.Exec(ctx, insertLane,
		arg.ID,
		arg.OriginID,
		arg.DestinationID,
		arg.Mode,
		arg.DistanceKm,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	return err
}

const updateLane = `-- name: UpdateLane :exec
UPDATE lanes SET mode = $2, distance_km = $3, updated_at = $4 WHERE id = $1
`

type UpdateLaneParams struct {
	ID         uuid.UUID          `db:"id" json:"id"`
	Mode       TransportMode      `db:"mode" json:"mode"`
	DistanceKm pgtype.Numeric     `db:"distance_km" json:"distance_km"`
	UpdatedAt  pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
}

func (q *Queries) UpdateLane(ctx context.Context, arg UpdateLaneParams) error {
	_, err := q.db.Exec(ctx, updateLane,
		arg.ID,
		arg.Mode,
		arg.DistanceKm,
		arg.UpdatedAt,
	)
	return err
}
