// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: location.sql

package sqlcgen

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const getLocationByID = `-- name: GetLocationByID :one
SELECT id, name, un_locode, country_code, type, geom, attributes, created_at, updated_at FROM locations WHERE id = $1
`

func (q *Queries) GetLocationByID(ctx context.Context, id uuid.UUID) (Location, error) {
	row := q.db.QueryRow(ctx, getLocationByID, id)
	var i Location
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.UnLocode,
		&i.CountryCode,
		&i.Type,
		&i.Geom,
		&i.Attributes,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getLocationByUnLocode = `-- name: GetLocationByUnLocode :one
SELECT id, name, un_locode, country_code, type, geom, attributes, created_at, updated_at FROM locations WHERE un_locode = $1
`

func (q *Queries) GetLocationByUnLocode(ctx context.Context, unLocode pgtype.Text) (Location, error) {
	row := q.db.QueryRow(ctx, getLocationByUnLocode, unLocode)
	var i Location
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.UnLocode,
		&i.CountryCode,
		&i.Type,
		&i.Geom,
		&i.Attributes,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const insertLocation = `-- name: InsertLocation :exec
INSERT INTO locations (id, name, un_locode, country_code, type, attributes, created_at, updated_at)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
`

type InsertLocationParams struct {
	ID          uuid.UUID          `db:"id" json:"id"`
	Name        string             `db:"name" json:"name"`
	UnLocode    pgtype.Text        `db:"un_locode" json:"un_locode"`
	CountryCode string             `db:"country_code" json:"country_code"`
	Type        LocationType       `db:"type" json:"type"`
	Attributes  []byte             `db:"attributes" json:"attributes"`
	CreatedAt   pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
}

func (q *Queries) InsertLocation(ctx context.Context, arg InsertLocationParams) error {
	_, err := q.db.Exec(ctx, insertLocation,
		arg.ID,
		arg.Name,
		arg.UnLocode,
		arg.CountryCode,
		arg.Type,
		arg.Attributes,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	return err
}

const listLocationsByCountry = `-- name: ListLocationsByCountry :many
SELECT id, name, un_locode, country_code, type, geom, attributes, created_at, updated_at FROM locations WHERE country_code = $1 ORDER BY name
`

func (q *Queries) ListLocationsByCountry(ctx context.Context, countryCode string) ([]Location, error) {
	rows, err := q.db.Query(ctx, listLocationsByCountry, countryCode)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Location
	for rows.Next() {
		var i Location
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.UnLocode,
			&i.CountryCode,
			&i.Type,
			&i.Geom,
			&i.Attributes,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateLocation = `-- name: UpdateLocation :exec
UPDATE locations
SET name = $2, un_locode = $3, country_code = $4, type = $5, attributes = $6, updated_at = $7
WHERE id = $1
`

type UpdateLocationParams struct {
	ID          uuid.UUID          `db:"id" json:"id"`
	Name        string             `db:"name" json:"name"`
	UnLocode    pgtype.Text        `db:"un_locode" json:"un_locode"`
	CountryCode string             `db:"country_code" json:"country_code"`
	Type        LocationType       `db:"type" json:"type"`
	Attributes  []byte             `db:"attributes" json:"attributes"`
	UpdatedAt   pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
}

func (q *Queries) UpdateLocation(ctx context.Context, arg UpdateLocationParams) error {
	_, err := q.db.Exec(ctx, updateLocation,
		arg.ID,
		arg.Name,
		arg.UnLocode,
		arg.CountryCode,
		arg.Type,
		arg.Attributes,
		arg.UpdatedAt,
	)
	return err
}
