// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: milestone.sql

package sqlcgen

import (
	"context"
	"encoding/json"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const insertMilestone = `-- name: InsertMilestone :exec
INSERT INTO shipment_milestones (
    id, shipment_id, milestone_type, occurred_at, recorded_at,
    source_document_id, source_doc_type, payload, sequence
) VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9)
`

type InsertMilestoneParams struct {
	ID               uuid.UUID          `db:"id" json:"id"`
	ShipmentID       uuid.UUID          `db:"shipment_id" json:"shipment_id"`
	MilestoneType    string             `db:"milestone_type" json:"milestone_type"`
	OccurredAt       pgtype.Timestamptz `db:"occurred_at" json:"occurred_at"`
	RecordedAt       pgtype.Timestamptz `db:"recorded_at" json:"recorded_at"`
	SourceDocumentID uuid.UUID          `db:"source_document_id" json:"source_document_id"`
	SourceDocType    string             `db:"source_doc_type" json:"source_doc_type"`
	Payload          json.RawMessage    `db:"payload" json:"payload"`
	Sequence         int32              `db:"sequence" json:"sequence"`
}

func (q *Queries) InsertMilestone(ctx context.Context, arg InsertMilestoneParams) error {
	_, err := q.db.Exec(ctx, insertMilestone,
		arg.ID,
		arg.ShipmentID,
		arg.MilestoneType,
		arg.OccurredAt,
		arg.RecordedAt,
		arg.SourceDocumentID,
		arg.SourceDocType,
		arg.Payload,
		arg.Sequence,
	)
	return err
}

const listMilestonesByShipmentID = `-- name: ListMilestonesByShipmentID :many
SELECT id, shipment_id, milestone_type, occurred_at, recorded_at, source_document_id, source_doc_type, payload, sequence FROM shipment_milestones WHERE shipment_id = $1 ORDER BY sequence
`

func (q *Queries) ListMilestonesByShipmentID(ctx context.Context, shipmentID uuid.UUID) ([]ShipmentMilestone, error) {
	rows, err := q.db.Query(ctx, listMilestonesByShipmentID, shipmentID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ShipmentMilestone
	for rows.Next() {
		var i ShipmentMilestone
		if err := rows.Scan(
			&i.ID,
			&i.ShipmentID,
			&i.MilestoneType,
			&i.OccurredAt,
			&i.RecordedAt,
			&i.SourceDocumentID,
			&i.SourceDocType,
			&i.Payload,
			&i.Sequence,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
