// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlcgen

import (
	"database/sql/driver"
	"encoding/json"
	"fmt"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
	"github.com/shopspring/decimal"
)

type ActionType string

const (
	ActionTypeDOCUMENTUPLOAD     ActionType = "DOCUMENT_UPLOAD"
	ActionTypeDOCUMENTGENERATION ActionType = "DOCUMENT_GENERATION"
	ActionTypeEMAILSEND          ActionType = "EMAIL_SEND"
	ActionTypeAPPROVALREQUEST    ActionType = "APPROVAL_REQUEST"
	ActionTypeEXTERNALAPICALL    ActionType = "EXTERNAL_API_CALL"
	ActionTypeMANUALCHECK        ActionType = "MANUAL_CHECK"
)

func (e *ActionType) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = ActionType(s)
	case string:
		*e = ActionType(s)
	default:
		return fmt.Errorf("unsupported scan type for ActionType: %T", src)
	}
	return nil
}

type NullActionType struct {
	ActionType ActionType `json:"action_type"`
	Valid      bool       `json:"valid"` // Valid is true if ActionType is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullActionType) Scan(value interface{}) error {
	if value == nil {
		ns.ActionType, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.ActionType.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullActionType) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.ActionType), nil
}

type ContractStatus string

const (
	ContractStatusDRAFT      ContractStatus = "DRAFT"
	ContractStatusCONTRACTED ContractStatus = "CONTRACTED"
	ContractStatusEXPIRED    ContractStatus = "EXPIRED"
	ContractStatusCANCELLED  ContractStatus = "CANCELLED"
)

func (e *ContractStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = ContractStatus(s)
	case string:
		*e = ContractStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for ContractStatus: %T", src)
	}
	return nil
}

type NullContractStatus struct {
	ContractStatus ContractStatus `json:"contract_status"`
	Valid          bool           `json:"valid"` // Valid is true if ContractStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullContractStatus) Scan(value interface{}) error {
	if value == nil {
		ns.ContractStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.ContractStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullContractStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.ContractStatus), nil
}

type CostCategory string

const (
	CostCategoryESTIMATED       CostCategory = "ESTIMATED"
	CostCategoryESTIMATEDACTUAL CostCategory = "ESTIMATED_ACTUAL"
	CostCategoryACTUAL          CostCategory = "ACTUAL"
)

func (e *CostCategory) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = CostCategory(s)
	case string:
		*e = CostCategory(s)
	default:
		return fmt.Errorf("unsupported scan type for CostCategory: %T", src)
	}
	return nil
}

type NullCostCategory struct {
	CostCategory CostCategory `json:"cost_category"`
	Valid        bool         `json:"valid"` // Valid is true if CostCategory is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullCostCategory) Scan(value interface{}) error {
	if value == nil {
		ns.CostCategory, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.CostCategory.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullCostCategory) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.CostCategory), nil
}

type DocumentOrigin string

const (
	DocumentOriginSHIPPER  DocumentOrigin = "SHIPPER"
	DocumentOriginPROVIDER DocumentOrigin = "PROVIDER"
)

func (e *DocumentOrigin) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = DocumentOrigin(s)
	case string:
		*e = DocumentOrigin(s)
	default:
		return fmt.Errorf("unsupported scan type for DocumentOrigin: %T", src)
	}
	return nil
}

type NullDocumentOrigin struct {
	DocumentOrigin DocumentOrigin `json:"document_origin"`
	Valid          bool           `json:"valid"` // Valid is true if DocumentOrigin is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullDocumentOrigin) Scan(value interface{}) error {
	if value == nil {
		ns.DocumentOrigin, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.DocumentOrigin.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullDocumentOrigin) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.DocumentOrigin), nil
}

type DocumentStatus string

const (
	DocumentStatusDRAFT             DocumentStatus = "DRAFT"
	DocumentStatusISSUED            DocumentStatus = "ISSUED"
	DocumentStatusUNDERREVIEW       DocumentStatus = "UNDER_REVIEW"
	DocumentStatusREVISIONREQUESTED DocumentStatus = "REVISION_REQUESTED"
	DocumentStatusCONFIRMED         DocumentStatus = "CONFIRMED"
	DocumentStatusARCHIVED          DocumentStatus = "ARCHIVED"
)

func (e *DocumentStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = DocumentStatus(s)
	case string:
		*e = DocumentStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for DocumentStatus: %T", src)
	}
	return nil
}

type NullDocumentStatus struct {
	DocumentStatus DocumentStatus `json:"document_status"`
	Valid          bool           `json:"valid"` // Valid is true if DocumentStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullDocumentStatus) Scan(value interface{}) error {
	if value == nil {
		ns.DocumentStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.DocumentStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullDocumentStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.DocumentStatus), nil
}

type LocationType string

const (
	LocationTypePORT          LocationType = "PORT"
	LocationTypeAIRPORT       LocationType = "AIRPORT"
	LocationTypeRAILTERMINAL  LocationType = "RAIL_TERMINAL"
	LocationTypeWAREHOUSE     LocationType = "WAREHOUSE"
	LocationTypeCONTAINERYARD LocationType = "CONTAINER_YARD"
	LocationTypeDOOR          LocationType = "DOOR"
	LocationTypeBORDER        LocationType = "BORDER"
)

func (e *LocationType) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = LocationType(s)
	case string:
		*e = LocationType(s)
	default:
		return fmt.Errorf("unsupported scan type for LocationType: %T", src)
	}
	return nil
}

type NullLocationType struct {
	LocationType LocationType `json:"location_type"`
	Valid        bool         `json:"valid"` // Valid is true if LocationType is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullLocationType) Scan(value interface{}) error {
	if value == nil {
		ns.LocationType, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.LocationType.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullLocationType) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.LocationType), nil
}

type OperatorRole string

const (
	OperatorRoleTRANSPORTER    OperatorRole = "TRANSPORTER"
	OperatorRoleWAREHOUSE      OperatorRole = "WAREHOUSE"
	OperatorRoleCUSTOMSBROKER  OperatorRole = "CUSTOMS_BROKER"
	OperatorRoleDELIVERYAGENT  OperatorRole = "DELIVERY_AGENT"
	OperatorRolePACKINGSERVICE OperatorRole = "PACKING_SERVICE"
	OperatorRoleINSPECTOR      OperatorRole = "INSPECTOR"
)

func (e *OperatorRole) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = OperatorRole(s)
	case string:
		*e = OperatorRole(s)
	default:
		return fmt.Errorf("unsupported scan type for OperatorRole: %T", src)
	}
	return nil
}

type NullOperatorRole struct {
	OperatorRole OperatorRole `json:"operator_role"`
	Valid        bool         `json:"valid"` // Valid is true if OperatorRole is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullOperatorRole) Scan(value interface{}) error {
	if value == nil {
		ns.OperatorRole, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.OperatorRole.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullOperatorRole) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.OperatorRole), nil
}

type ProviderType string

const (
	ProviderTypeCARRIER       ProviderType = "CARRIER"
	ProviderTypeFORWARDER     ProviderType = "FORWARDER"
	ProviderTypeWAREHOUSE     ProviderType = "WAREHOUSE"
	ProviderTypeCUSTOMSBROKER ProviderType = "CUSTOMS_BROKER"
	ProviderTypeTRUCKER       ProviderType = "TRUCKER"
)

func (e *ProviderType) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = ProviderType(s)
	case string:
		*e = ProviderType(s)
	default:
		return fmt.Errorf("unsupported scan type for ProviderType: %T", src)
	}
	return nil
}

type NullProviderType struct {
	ProviderType ProviderType `json:"provider_type"`
	Valid        bool         `json:"valid"` // Valid is true if ProviderType is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullProviderType) Scan(value interface{}) error {
	if value == nil {
		ns.ProviderType, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.ProviderType.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullProviderType) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.ProviderType), nil
}

type RateStatus string

const (
	RateStatusDRAFT   RateStatus = "DRAFT"
	RateStatusACTIVE  RateStatus = "ACTIVE"
	RateStatusEXPIRED RateStatus = "EXPIRED"
)

func (e *RateStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = RateStatus(s)
	case string:
		*e = RateStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for RateStatus: %T", src)
	}
	return nil
}

type NullRateStatus struct {
	RateStatus RateStatus `json:"rate_status"`
	Valid      bool       `json:"valid"` // Valid is true if RateStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullRateStatus) Scan(value interface{}) error {
	if value == nil {
		ns.RateStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.RateStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullRateStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.RateStatus), nil
}

type ShipmentStatus string

const (
	ShipmentStatusPLANNED   ShipmentStatus = "PLANNED"
	ShipmentStatusBOOKED    ShipmentStatus = "BOOKED"
	ShipmentStatusINTRANSIT ShipmentStatus = "IN_TRANSIT"
	ShipmentStatusARRIVED   ShipmentStatus = "ARRIVED"
	ShipmentStatusDELIVERED ShipmentStatus = "DELIVERED"
	ShipmentStatusCANCELLED ShipmentStatus = "CANCELLED"
)

func (e *ShipmentStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = ShipmentStatus(s)
	case string:
		*e = ShipmentStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for ShipmentStatus: %T", src)
	}
	return nil
}

type NullShipmentStatus struct {
	ShipmentStatus ShipmentStatus `json:"shipment_status"`
	Valid          bool           `json:"valid"` // Valid is true if ShipmentStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullShipmentStatus) Scan(value interface{}) error {
	if value == nil {
		ns.ShipmentStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.ShipmentStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullShipmentStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.ShipmentStatus), nil
}

type SopDefinitionStatus string

const (
	SopDefinitionStatusDRAFT    SopDefinitionStatus = "DRAFT"
	SopDefinitionStatusACTIVE   SopDefinitionStatus = "ACTIVE"
	SopDefinitionStatusARCHIVED SopDefinitionStatus = "ARCHIVED"
)

func (e *SopDefinitionStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = SopDefinitionStatus(s)
	case string:
		*e = SopDefinitionStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for SopDefinitionStatus: %T", src)
	}
	return nil
}

type NullSopDefinitionStatus struct {
	SopDefinitionStatus SopDefinitionStatus `json:"sop_definition_status"`
	Valid               bool                `json:"valid"` // Valid is true if SopDefinitionStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullSopDefinitionStatus) Scan(value interface{}) error {
	if value == nil {
		ns.SopDefinitionStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.SopDefinitionStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullSopDefinitionStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.SopDefinitionStatus), nil
}

type SopInstanceStatus string

const (
	SopInstanceStatusINPROGRESS SopInstanceStatus = "IN_PROGRESS"
	SopInstanceStatusCOMPLETED  SopInstanceStatus = "COMPLETED"
	SopInstanceStatusCANCELLED  SopInstanceStatus = "CANCELLED"
)

func (e *SopInstanceStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = SopInstanceStatus(s)
	case string:
		*e = SopInstanceStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for SopInstanceStatus: %T", src)
	}
	return nil
}

type NullSopInstanceStatus struct {
	SopInstanceStatus SopInstanceStatus `json:"sop_instance_status"`
	Valid             bool              `json:"valid"` // Valid is true if SopInstanceStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullSopInstanceStatus) Scan(value interface{}) error {
	if value == nil {
		ns.SopInstanceStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.SopInstanceStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullSopInstanceStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.SopInstanceStatus), nil
}

type StandardRouteStatus string

const (
	StandardRouteStatusACTIVE   StandardRouteStatus = "ACTIVE"
	StandardRouteStatusARCHIVED StandardRouteStatus = "ARCHIVED"
)

func (e *StandardRouteStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = StandardRouteStatus(s)
	case string:
		*e = StandardRouteStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for StandardRouteStatus: %T", src)
	}
	return nil
}

type NullStandardRouteStatus struct {
	StandardRouteStatus StandardRouteStatus `json:"standard_route_status"`
	Valid               bool                `json:"valid"` // Valid is true if StandardRouteStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullStandardRouteStatus) Scan(value interface{}) error {
	if value == nil {
		ns.StandardRouteStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.StandardRouteStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullStandardRouteStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.StandardRouteStatus), nil
}

type TaskStatus string

const (
	TaskStatusPENDING    TaskStatus = "PENDING"
	TaskStatusINPROGRESS TaskStatus = "IN_PROGRESS"
	TaskStatusCOMPLETED  TaskStatus = "COMPLETED"
	TaskStatusSKIPPED    TaskStatus = "SKIPPED"
	TaskStatusERROR      TaskStatus = "ERROR"
)

func (e *TaskStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = TaskStatus(s)
	case string:
		*e = TaskStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for TaskStatus: %T", src)
	}
	return nil
}

type NullTaskStatus struct {
	TaskStatus TaskStatus `json:"task_status"`
	Valid      bool       `json:"valid"` // Valid is true if TaskStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullTaskStatus) Scan(value interface{}) error {
	if value == nil {
		ns.TaskStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.TaskStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullTaskStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.TaskStatus), nil
}

type TrackingNumberType string

const (
	TrackingNumberTypeCONTAINER     TrackingNumberType = "CONTAINER"
	TrackingNumberTypeAIRWAYBILL    TrackingNumberType = "AIRWAY_BILL"
	TrackingNumberTypeBILLOFLADING  TrackingNumberType = "BILL_OF_LADING"
	TrackingNumberTypeBOOKINGNUMBER TrackingNumberType = "BOOKING_NUMBER"
)

func (e *TrackingNumberType) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = TrackingNumberType(s)
	case string:
		*e = TrackingNumberType(s)
	default:
		return fmt.Errorf("unsupported scan type for TrackingNumberType: %T", src)
	}
	return nil
}

type NullTrackingNumberType struct {
	TrackingNumberType TrackingNumberType `json:"tracking_number_type"`
	Valid              bool               `json:"valid"` // Valid is true if TrackingNumberType is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullTrackingNumberType) Scan(value interface{}) error {
	if value == nil {
		ns.TrackingNumberType, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.TrackingNumberType.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullTrackingNumberType) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.TrackingNumberType), nil
}

type TrackingSourceType string

const (
	TrackingSourceTypeSEARATESAPI TrackingSourceType = "SEARATES_API"
	TrackingSourceTypeMANUALINPUT TrackingSourceType = "MANUAL_INPUT"
	TrackingSourceTypePARTNEREDI  TrackingSourceType = "PARTNER_EDI"
	TrackingSourceTypeDRIVERAPP   TrackingSourceType = "DRIVER_APP"
	TrackingSourceTypeIOTDEVICE   TrackingSourceType = "IOT_DEVICE"
)

func (e *TrackingSourceType) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = TrackingSourceType(s)
	case string:
		*e = TrackingSourceType(s)
	default:
		return fmt.Errorf("unsupported scan type for TrackingSourceType: %T", src)
	}
	return nil
}

type NullTrackingSourceType struct {
	TrackingSourceType TrackingSourceType `json:"tracking_source_type"`
	Valid              bool               `json:"valid"` // Valid is true if TrackingSourceType is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullTrackingSourceType) Scan(value interface{}) error {
	if value == nil {
		ns.TrackingSourceType, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.TrackingSourceType.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullTrackingSourceType) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.TrackingSourceType), nil
}

type TrackingStatus string

const (
	TrackingStatusBOOKED    TrackingStatus = "BOOKED"
	TrackingStatusINTRANSIT TrackingStatus = "IN_TRANSIT"
	TrackingStatusEXCEPTION TrackingStatus = "EXCEPTION"
	TrackingStatusARRIVED   TrackingStatus = "ARRIVED"
)

func (e *TrackingStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = TrackingStatus(s)
	case string:
		*e = TrackingStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for TrackingStatus: %T", src)
	}
	return nil
}

type NullTrackingStatus struct {
	TrackingStatus TrackingStatus `json:"tracking_status"`
	Valid          bool           `json:"valid"` // Valid is true if TrackingStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullTrackingStatus) Scan(value interface{}) error {
	if value == nil {
		ns.TrackingStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.TrackingStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullTrackingStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.TrackingStatus), nil
}

type TransportMode string

const (
	TransportModeOCEAN   TransportMode = "OCEAN"
	TransportModeAIR     TransportMode = "AIR"
	TransportModeTRUCK   TransportMode = "TRUCK"
	TransportModeRailway TransportMode = "Railway"
)

func (e *TransportMode) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = TransportMode(s)
	case string:
		*e = TransportMode(s)
	default:
		return fmt.Errorf("unsupported scan type for TransportMode: %T", src)
	}
	return nil
}

type NullTransportMode struct {
	TransportMode TransportMode `json:"transport_mode"`
	Valid         bool          `json:"valid"` // Valid is true if TransportMode is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullTransportMode) Scan(value interface{}) error {
	if value == nil {
		ns.TransportMode, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.TransportMode.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullTransportMode) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.TransportMode), nil
}

type Document struct {
	ID         uuid.UUID          `db:"id" json:"id"`
	ShipmentID uuid.UUID          `db:"shipment_id" json:"shipment_id"`
	DocType    string             `db:"doc_type" json:"doc_type"`
	Origin     DocumentOrigin     `db:"origin" json:"origin"`
	FileName   string             `db:"file_name" json:"file_name"`
	MimeType   pgtype.Text        `db:"mime_type" json:"mime_type"`
	StorageUri string             `db:"storage_uri" json:"storage_uri"`
	FileSize   int64              `db:"file_size" json:"file_size"`
	UploadedBy uuid.UUID          `db:"uploaded_by" json:"uploaded_by"`
	Status     DocumentStatus     `db:"status" json:"status"`
	Version    int32              `db:"version" json:"version"`
	Metadata   json.RawMessage    `db:"metadata" json:"metadata"`
	Content    []byte             `db:"content" json:"content"`
	CreatedAt  pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt  pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
}

type DocumentReview struct {
	ID            uuid.UUID          `db:"id" json:"id"`
	DocumentID    uuid.UUID          `db:"document_id" json:"document_id"`
	ReviewerID    uuid.UUID          `db:"reviewer_id" json:"reviewer_id"`
	ReviewedAt    pgtype.Timestamptz `db:"reviewed_at" json:"reviewed_at"`
	Decision      string             `db:"decision" json:"decision"`
	Comment       pgtype.Text        `db:"comment" json:"comment"`
	Discrepancies json.RawMessage    `db:"discrepancies" json:"discrepancies"`
}

type DomainEvent struct {
	ID            uuid.UUID          `db:"id" json:"id"`
	EventType     string             `db:"event_type" json:"event_type"`
	AggregateID   uuid.UUID          `db:"aggregate_id" json:"aggregate_id"`
	AggregateType string             `db:"aggregate_type" json:"aggregate_type"`
	Payload       json.RawMessage    `db:"payload" json:"payload"`
	OccurredAt    pgtype.Timestamptz `db:"occurred_at" json:"occurred_at"`
	Published     bool               `db:"published" json:"published"`
	PublishedAt   pgtype.Timestamptz `db:"published_at" json:"published_at"`
	CreatedAt     pgtype.Timestamptz `db:"created_at" json:"created_at"`
}

type Lane struct {
	ID            uuid.UUID          `db:"id" json:"id"`
	OriginID      uuid.UUID          `db:"origin_id" json:"origin_id"`
	DestinationID uuid.UUID          `db:"destination_id" json:"destination_id"`
	Mode          TransportMode      `db:"mode" json:"mode"`
	DistanceKm    pgtype.Numeric     `db:"distance_km" json:"distance_km"`
	CreatedAt     pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt     pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
}

type Location struct {
	ID          uuid.UUID          `db:"id" json:"id"`
	Name        string             `db:"name" json:"name"`
	UnLocode    pgtype.Text        `db:"un_locode" json:"un_locode"`
	CountryCode string             `db:"country_code" json:"country_code"`
	Type        LocationType       `db:"type" json:"type"`
	Geom        interface{}        `db:"geom" json:"geom"`
	Attributes  []byte             `db:"attributes" json:"attributes"`
	CreatedAt   pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
}

type LogisticsResource struct {
	ProviderID   uuid.UUID          `db:"provider_id" json:"provider_id"`
	Name         string             `db:"name" json:"name"`
	IsAvailable  bool               `db:"is_available" json:"is_available"`
	Capabilities json.RawMessage    `db:"capabilities" json:"capabilities"`
	CreatedAt    pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt    pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
}

type Rate struct {
	ID        uuid.UUID          `db:"id" json:"id"`
	ShipperID uuid.UUID          `db:"shipper_id" json:"shipper_id"`
	Name      string             `db:"name" json:"name"`
	Status    RateStatus         `db:"status" json:"status"`
	ValidFrom pgtype.Timestamptz `db:"valid_from" json:"valid_from"`
	ValidTo   pgtype.Timestamptz `db:"valid_to" json:"valid_to"`
	CreatedAt pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
}

type RateEntry struct {
	ID                uuid.UUID         `db:"id" json:"id"`
	RateID            uuid.UUID         `db:"rate_id" json:"rate_id"`
	ProviderID        uuid.UUID         `db:"provider_id" json:"provider_id"`
	ContractID        uuid.UUID         `db:"contract_id" json:"contract_id"`
	TariffID          uuid.UUID         `db:"tariff_id" json:"tariff_id"`
	OriginID          pgtype.UUID       `db:"origin_id" json:"origin_id"`
	DestinationID     pgtype.UUID       `db:"destination_id" json:"destination_id"`
	TransportMode     NullTransportMode `db:"transport_mode" json:"transport_mode"`
	TariffLineItemID  uuid.UUID         `db:"tariff_line_item_id" json:"tariff_line_item_id"`
	ChargeCode        string            `db:"charge_code" json:"charge_code"`
	Category          string            `db:"category" json:"category"`
	UnitPriceAmount   decimal.Decimal   `db:"unit_price_amount" json:"unit_price_amount"`
	UnitPriceCurrency string            `db:"unit_price_currency" json:"unit_price_currency"`
}

type ServiceContract struct {
	ID         uuid.UUID          `db:"id" json:"id"`
	ProviderID uuid.UUID          `db:"provider_id" json:"provider_id"`
	ShipperID  uuid.UUID          `db:"shipper_id" json:"shipper_id"`
	Status     ContractStatus     `db:"status" json:"status"`
	ValidFrom  pgtype.Timestamptz `db:"valid_from" json:"valid_from"`
	ValidTo    pgtype.Timestamptz `db:"valid_to" json:"valid_to"`
	CreatedAt  pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt  pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
}

type ServiceOperator struct {
	ProviderID          uuid.UUID          `db:"provider_id" json:"provider_id"`
	Name                string             `db:"name" json:"name"`
	Role                OperatorRole       `db:"role" json:"role"`
	OperationalContacts json.RawMessage    `db:"operational_contacts" json:"operational_contacts"`
	PerformanceMetrics  json.RawMessage    `db:"performance_metrics" json:"performance_metrics"`
	IntegrationChannels json.RawMessage    `db:"integration_channels" json:"integration_channels"`
	CreatedAt           pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt           pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
}

type Shipment struct {
	ID                    uuid.UUID          `db:"id" json:"id"`
	ShipmentNo            string             `db:"shipment_no" json:"shipment_no"`
	ShipperID             uuid.UUID          `db:"shipper_id" json:"shipper_id"`
	ConsigneeID           uuid.UUID          `db:"consignee_id" json:"consignee_id"`
	Status                ShipmentStatus     `db:"status" json:"status"`
	StandardRouteID       pgtype.UUID        `db:"standard_route_id" json:"standard_route_id"`
	RateID                pgtype.UUID        `db:"rate_id" json:"rate_id"`
	OriginLocationID      uuid.UUID          `db:"origin_location_id" json:"origin_location_id"`
	DestLocationID        uuid.UUID          `db:"dest_location_id" json:"dest_location_id"`
	TransportRequirements []byte             `db:"transport_requirements" json:"transport_requirements"`
	CostIsFinalized       bool               `db:"cost_is_finalized" json:"cost_is_finalized"`
	CostFinalizedAt       pgtype.Timestamptz `db:"cost_finalized_at" json:"cost_finalized_at"`
	CreatedAt             pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt             pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
}

type ShipmentCostLineItem struct {
	ID           uuid.UUID       `db:"id" json:"id"`
	ShipmentID   uuid.UUID       `db:"shipment_id" json:"shipment_id"`
	CostCategory CostCategory    `db:"cost_category" json:"cost_category"`
	ChargeCode   string          `db:"charge_code" json:"charge_code"`
	ChargeName   pgtype.Text     `db:"charge_name" json:"charge_name"`
	Category     pgtype.Text     `db:"category" json:"category"`
	Amount       decimal.Decimal `db:"amount" json:"amount"`
	Currency     string          `db:"currency" json:"currency"`
	Quantity     pgtype.Numeric  `db:"quantity" json:"quantity"`
	UnitPrice    pgtype.Numeric  `db:"unit_price" json:"unit_price"`
	UnitCurrency pgtype.Text     `db:"unit_currency" json:"unit_currency"`
	AppliedScope pgtype.Text     `db:"applied_scope" json:"applied_scope"`
	Remarks      pgtype.Text     `db:"remarks" json:"remarks"`
	SegmentID    pgtype.UUID     `db:"segment_id" json:"segment_id"`
	SegmentIndex pgtype.Int4     `db:"segment_index" json:"segment_index"`
}

type ShipmentCostSummary struct {
	ID              uuid.UUID          `db:"id" json:"id"`
	ShipmentID      uuid.UUID          `db:"shipment_id" json:"shipment_id"`
	CostCategory    CostCategory       `db:"cost_category" json:"cost_category"`
	RateID          pgtype.UUID        `db:"rate_id" json:"rate_id"`
	InvoiceID       pgtype.UUID        `db:"invoice_id" json:"invoice_id"`
	InvoiceNo       pgtype.Text        `db:"invoice_no" json:"invoice_no"`
	ProviderID      pgtype.UUID        `db:"provider_id" json:"provider_id"`
	TotalAmount     decimal.Decimal    `db:"total_amount" json:"total_amount"`
	TotalCurrency   string             `db:"total_currency" json:"total_currency"`
	CalculatedAt    pgtype.Timestamptz `db:"calculated_at" json:"calculated_at"`
	CalculationBase pgtype.Text        `db:"calculation_base" json:"calculation_base"`
}

type ShipmentItem struct {
	ID                 uuid.UUID       `db:"id" json:"id"`
	ShipmentID         uuid.UUID       `db:"shipment_id" json:"shipment_id"`
	Commodity          string          `db:"commodity" json:"commodity"`
	HsCode             pgtype.Text     `db:"hs_code" json:"hs_code"`
	Quantity           decimal.Decimal `db:"quantity" json:"quantity"`
	WeightKg           decimal.Decimal `db:"weight_kg" json:"weight_kg"`
	VolumeM3           decimal.Decimal `db:"volume_m3" json:"volume_m3"`
	PackageType        pgtype.Text     `db:"package_type" json:"package_type"`
	LoadedOnTrackingID pgtype.UUID     `db:"loaded_on_tracking_id" json:"loaded_on_tracking_id"`
	Attributes         []byte          `db:"attributes" json:"attributes"`
}

type ShipmentMilestone struct {
	ID               uuid.UUID          `db:"id" json:"id"`
	ShipmentID       uuid.UUID          `db:"shipment_id" json:"shipment_id"`
	MilestoneType    string             `db:"milestone_type" json:"milestone_type"`
	OccurredAt       pgtype.Timestamptz `db:"occurred_at" json:"occurred_at"`
	RecordedAt       pgtype.Timestamptz `db:"recorded_at" json:"recorded_at"`
	SourceDocumentID uuid.UUID          `db:"source_document_id" json:"source_document_id"`
	SourceDocType    string             `db:"source_doc_type" json:"source_doc_type"`
	Payload          json.RawMessage    `db:"payload" json:"payload"`
	Sequence         int32              `db:"sequence" json:"sequence"`
}

type ShipmentPlannedRouteSegment struct {
	ID               uuid.UUID      `db:"id" json:"id"`
	ShipmentID       uuid.UUID      `db:"shipment_id" json:"shipment_id"`
	SequenceOrder    int32          `db:"sequence_order" json:"sequence_order"`
	OriginLocationID uuid.UUID      `db:"origin_location_id" json:"origin_location_id"`
	OriginType       LocationType   `db:"origin_type" json:"origin_type"`
	DestLocationID   uuid.UUID      `db:"dest_location_id" json:"dest_location_id"`
	DestType         LocationType   `db:"dest_type" json:"dest_type"`
	Mode             TransportMode  `db:"mode" json:"mode"`
	DistanceKm       pgtype.Numeric `db:"distance_km" json:"distance_km"`
	MasterLaneID     pgtype.UUID    `db:"master_lane_id" json:"master_lane_id"`
}

type ShipmentTrackingUnit struct {
	ShipmentID     uuid.UUID `db:"shipment_id" json:"shipment_id"`
	TrackingUnitID uuid.UUID `db:"tracking_unit_id" json:"tracking_unit_id"`
}

type SopDefinition struct {
	ID            uuid.UUID           `db:"id" json:"id"`
	Name          string              `db:"name" json:"name"`
	Description   pgtype.Text         `db:"description" json:"description"`
	Direction     string              `db:"direction" json:"direction"`
	TransportMode TransportMode       `db:"transport_mode" json:"transport_mode"`
	OriginCountry pgtype.Text         `db:"origin_country" json:"origin_country"`
	DestCountry   pgtype.Text         `db:"dest_country" json:"dest_country"`
	Status        SopDefinitionStatus `db:"status" json:"status"`
	Version       int32               `db:"version" json:"version"`
	CreatedAt     pgtype.Timestamptz  `db:"created_at" json:"created_at"`
	UpdatedAt     pgtype.Timestamptz  `db:"updated_at" json:"updated_at"`
}

type SopInstance struct {
	ID             uuid.UUID          `db:"id" json:"id"`
	ShipmentID     uuid.UUID          `db:"shipment_id" json:"shipment_id"`
	DefinitionID   uuid.UUID          `db:"definition_id" json:"definition_id"`
	DefinitionName string             `db:"definition_name" json:"definition_name"`
	Status         SopInstanceStatus  `db:"status" json:"status"`
	CreatedAt      pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt      pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
}

type SopStepDefinition struct {
	ID               uuid.UUID       `db:"id" json:"id"`
	SopDefinitionID  uuid.UUID       `db:"sop_definition_id" json:"sop_definition_id"`
	Name             string          `db:"name" json:"name"`
	Description      pgtype.Text     `db:"description" json:"description"`
	OrderIndex       int32           `db:"order_index" json:"order_index"`
	RequiredDocTypes json.RawMessage `db:"required_doc_types" json:"required_doc_types"`
	GeneratedDocType pgtype.Text     `db:"generated_doc_type" json:"generated_doc_type"`
	ActionType       ActionType      `db:"action_type" json:"action_type"`
	IsAutomatable    bool            `db:"is_automatable" json:"is_automatable"`
}

type SopTask struct {
	ID                uuid.UUID          `db:"id" json:"id"`
	SopInstanceID     uuid.UUID          `db:"sop_instance_id" json:"sop_instance_id"`
	StepDefinitionID  uuid.UUID          `db:"step_definition_id" json:"step_definition_id"`
	Name              string             `db:"name" json:"name"`
	Description       pgtype.Text        `db:"description" json:"description"`
	OrderIndex        int32              `db:"order_index" json:"order_index"`
	ActionType        ActionType         `db:"action_type" json:"action_type"`
	RequiredDocTypes  json.RawMessage    `db:"required_doc_types" json:"required_doc_types"`
	GeneratedDocType  pgtype.Text        `db:"generated_doc_type" json:"generated_doc_type"`
	Status            TaskStatus         `db:"status" json:"status"`
	AssigneeID        pgtype.UUID        `db:"assignee_id" json:"assignee_id"`
	LinkedDocumentIds json.RawMessage    `db:"linked_document_ids" json:"linked_document_ids"`
	CompletedAt       pgtype.Timestamptz `db:"completed_at" json:"completed_at"`
	CompletedBy       pgtype.UUID        `db:"completed_by" json:"completed_by"`
	Note              pgtype.Text        `db:"note" json:"note"`
}

type StandardRoute struct {
	ID                    uuid.UUID           `db:"id" json:"id"`
	Name                  string              `db:"name" json:"name"`
	ShipperID             uuid.UUID           `db:"shipper_id" json:"shipper_id"`
	OriginLocationID      uuid.UUID           `db:"origin_location_id" json:"origin_location_id"`
	DestinationLocationID uuid.UUID           `db:"destination_location_id" json:"destination_location_id"`
	Status                StandardRouteStatus `db:"status" json:"status"`
	StandardLeadTimeDays  int32               `db:"standard_lead_time_days" json:"standard_lead_time_days"`
	TargetCostAmount      pgtype.Numeric      `db:"target_cost_amount" json:"target_cost_amount"`
	TargetCostCurrency    pgtype.Text         `db:"target_cost_currency" json:"target_cost_currency"`
	ValidFrom             pgtype.Timestamptz  `db:"valid_from" json:"valid_from"`
	ValidTo               pgtype.Timestamptz  `db:"valid_to" json:"valid_to"`
	CreatedAt             pgtype.Timestamptz  `db:"created_at" json:"created_at"`
	UpdatedAt             pgtype.Timestamptz  `db:"updated_at" json:"updated_at"`
}

type StandardRouteLeg struct {
	ID                  uuid.UUID     `db:"id" json:"id"`
	StandardRouteID     uuid.UUID     `db:"standard_route_id" json:"standard_route_id"`
	SequenceOrder       int32         `db:"sequence_order" json:"sequence_order"`
	OriginLocationID    uuid.UUID     `db:"origin_location_id" json:"origin_location_id"`
	DestLocationID      uuid.UUID     `db:"dest_location_id" json:"dest_location_id"`
	TargetMode          TransportMode `db:"target_mode" json:"target_mode"`
	StandardTransitDays int32         `db:"standard_transit_days" json:"standard_transit_days"`
	MasterLaneID        pgtype.UUID   `db:"master_lane_id" json:"master_lane_id"`
}

type Tariff struct {
	ID            uuid.UUID          `db:"id" json:"id"`
	ContractID    uuid.UUID          `db:"contract_id" json:"contract_id"`
	Name          string             `db:"name" json:"name"`
	Version       int32              `db:"version" json:"version"`
	BaseVersionID pgtype.UUID        `db:"base_version_id" json:"base_version_id"`
	EffectiveFrom pgtype.Timestamptz `db:"effective_from" json:"effective_from"`
	EffectiveTo   pgtype.Timestamptz `db:"effective_to" json:"effective_to"`
	CreatedAt     pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt     pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
}

type TariffLineItem struct {
	ID         uuid.UUID          `db:"id" json:"id"`
	TariffID   uuid.UUID          `db:"tariff_id" json:"tariff_id"`
	ChargeCode string             `db:"charge_code" json:"charge_code"`
	Category   string             `db:"category" json:"category"`
	Scope      json.RawMessage    `db:"scope" json:"scope"`
	Logic      json.RawMessage    `db:"logic" json:"logic"`
	CreatedAt  pgtype.Timestamptz `db:"created_at" json:"created_at"`
}

type TrackingEvent struct {
	ID          uuid.UUID          `db:"id" json:"id"`
	SegmentID   uuid.UUID          `db:"segment_id" json:"segment_id"`
	Timestamp   pgtype.Timestamptz `db:"timestamp" json:"timestamp"`
	Source      TrackingSourceType `db:"source" json:"source"`
	Code        string             `db:"code" json:"code"`
	Description pgtype.Text        `db:"description" json:"description"`
	LocationRaw pgtype.Text        `db:"location_raw" json:"location_raw"`
	RawPayload  pgtype.Text        `db:"raw_payload" json:"raw_payload"`
}

type TrackingSegment struct {
	ID                     uuid.UUID          `db:"id" json:"id"`
	TrackingUnitID         uuid.UUID          `db:"tracking_unit_id" json:"tracking_unit_id"`
	ActualOriginLocationID uuid.UUID          `db:"actual_origin_location_id" json:"actual_origin_location_id"`
	ActualDestLocationID   uuid.UUID          `db:"actual_dest_location_id" json:"actual_dest_location_id"`
	Mode                   TransportMode      `db:"mode" json:"mode"`
	CarrierTrackingNumber  pgtype.Text        `db:"carrier_tracking_number" json:"carrier_tracking_number"`
	PrimarySource          TrackingSourceType `db:"primary_source" json:"primary_source"`
	Status                 TrackingStatus     `db:"status" json:"status"`
	ActualDeparture        pgtype.Timestamptz `db:"actual_departure" json:"actual_departure"`
	ActualArrival          pgtype.Timestamptz `db:"actual_arrival" json:"actual_arrival"`
	EstimatedArrival       pgtype.Timestamptz `db:"estimated_arrival" json:"estimated_arrival"`
}

type TrackingUnit struct {
	ID                 uuid.UUID          `db:"id" json:"id"`
	TrackingNumber     string             `db:"tracking_number" json:"tracking_number"`
	TrackingNumberType TrackingNumberType `db:"tracking_number_type" json:"tracking_number_type"`
	CarrierID          uuid.UUID          `db:"carrier_id" json:"carrier_id"`
	CurrentStatus      TrackingStatus     `db:"current_status" json:"current_status"`
	LastUpdated        pgtype.Timestamptz `db:"last_updated" json:"last_updated"`
}

type Vendor struct {
	ID              uuid.UUID          `db:"id" json:"id"`
	Name            string             `db:"name" json:"name"`
	Type            ProviderType       `db:"type" json:"type"`
	CreditRating    string             `db:"credit_rating" json:"credit_rating"`
	PaymentDays     int32              `db:"payment_days" json:"payment_days"`
	PaymentCurrency string             `db:"payment_currency" json:"payment_currency"`
	PreferredVendor bool               `db:"preferred_vendor" json:"preferred_vendor"`
	Capabilities    json.RawMessage    `db:"capabilities" json:"capabilities"`
	Contacts        json.RawMessage    `db:"contacts" json:"contacts"`
	CreatedAt       pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt       pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
}
