// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: rate.sql

package sqlcgen

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
	"github.com/shopspring/decimal"
)

const deleteRate = `-- name: DeleteRate :exec
DELETE FROM rates WHERE id = $1
`

func (q *Queries) DeleteRate(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteRate, id)
	return err
}

const deleteRateEntriesByRateID = `-- name: DeleteRateEntriesByRateID :exec
DELETE FROM rate_entries WHERE rate_id = $1
`

func (q *Queries) DeleteRateEntriesByRateID(ctx context.Context, rateID uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteRateEntriesByRateID, rateID)
	return err
}

const getRateByID = `-- name: GetRateByID :one
SELECT id, shipper_id, name, status, valid_from, valid_to, created_at, updated_at FROM rates WHERE id = $1
`

func (q *Queries) GetRateByID(ctx context.Context, id uuid.UUID) (Rate, error) {
	row := q.db.QueryRow(ctx, getRateByID, id)
	var i Rate
	err := row.Scan(
		&i.ID,
		&i.ShipperID,
		&i.Name,
		&i.Status,
		&i.ValidFrom,
		&i.ValidTo,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const insertRate = `-- name: InsertRate :exec
INSERT INTO rates (id, shipper_id, name, status, valid_from, valid_to, created_at, updated_at)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
`

type InsertRateParams struct {
	ID        uuid.UUID          `db:"id" json:"id"`
	ShipperID uuid.UUID          `db:"shipper_id" json:"shipper_id"`
	Name      string             `db:"name" json:"name"`
	Status    RateStatus         `db:"status" json:"status"`
	ValidFrom pgtype.Timestamptz `db:"valid_from" json:"valid_from"`
	ValidTo   pgtype.Timestamptz `db:"valid_to" json:"valid_to"`
	CreatedAt pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
}

func (q *Queries) InsertRate(ctx context.Context, arg InsertRateParams) error {
	_, err := q.db.Exec(ctx, insertRate,
		arg.ID,
		arg.ShipperID,
		arg.Name,
		arg.Status,
		arg.ValidFrom,
		arg.ValidTo,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	return err
}

const insertRateEntry = `-- name: InsertRateEntry :exec
INSERT INTO rate_entries (
    id, rate_id, provider_id, contract_id, tariff_id,
    tariff_line_item_id, origin_id, destination_id, transport_mode,
    charge_code, category, unit_price_amount, unit_price_currency
) VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13)
`

type InsertRateEntryParams struct {
	ID                uuid.UUID         `db:"id" json:"id"`
	RateID            uuid.UUID         `db:"rate_id" json:"rate_id"`
	ProviderID        uuid.UUID         `db:"provider_id" json:"provider_id"`
	ContractID        uuid.UUID         `db:"contract_id" json:"contract_id"`
	TariffID          uuid.UUID         `db:"tariff_id" json:"tariff_id"`
	TariffLineItemID  uuid.UUID         `db:"tariff_line_item_id" json:"tariff_line_item_id"`
	OriginID          pgtype.UUID       `db:"origin_id" json:"origin_id"`
	DestinationID     pgtype.UUID       `db:"destination_id" json:"destination_id"`
	TransportMode     NullTransportMode `db:"transport_mode" json:"transport_mode"`
	ChargeCode        string            `db:"charge_code" json:"charge_code"`
	Category          string            `db:"category" json:"category"`
	UnitPriceAmount   decimal.Decimal   `db:"unit_price_amount" json:"unit_price_amount"`
	UnitPriceCurrency string            `db:"unit_price_currency" json:"unit_price_currency"`
}

func (q *Queries) InsertRateEntry(ctx context.Context, arg InsertRateEntryParams) error {
	_, err := q.db.Exec(ctx, insertRateEntry,
		arg.ID,
		arg.RateID,
		arg.ProviderID,
		arg.ContractID,
		arg.TariffID,
		arg.TariffLineItemID,
		arg.OriginID,
		arg.DestinationID,
		arg.TransportMode,
		arg.ChargeCode,
		arg.Category,
		arg.UnitPriceAmount,
		arg.UnitPriceCurrency,
	)
	return err
}

const listActiveRatesByShipper = `-- name: ListActiveRatesByShipper :many
SELECT id, shipper_id, name, status, valid_from, valid_to, created_at, updated_at FROM rates WHERE shipper_id = $1 AND status = 'ACTIVE' ORDER BY name
`

func (q *Queries) ListActiveRatesByShipper(ctx context.Context, shipperID uuid.UUID) ([]Rate, error) {
	rows, err := q.db.Query(ctx, listActiveRatesByShipper, shipperID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Rate
	for rows.Next() {
		var i Rate
		if err := rows.Scan(
			&i.ID,
			&i.ShipperID,
			&i.Name,
			&i.Status,
			&i.ValidFrom,
			&i.ValidTo,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRateEntriesByRateID = `-- name: ListRateEntriesByRateID :many
SELECT id, rate_id, provider_id, contract_id, tariff_id, origin_id, destination_id, transport_mode, tariff_line_item_id, charge_code, category, unit_price_amount, unit_price_currency FROM rate_entries WHERE rate_id = $1
`

func (q *Queries) ListRateEntriesByRateID(ctx context.Context, rateID uuid.UUID) ([]RateEntry, error) {
	rows, err := q.db.Query(ctx, listRateEntriesByRateID, rateID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []RateEntry
	for rows.Next() {
		var i RateEntry
		if err := rows.Scan(
			&i.ID,
			&i.RateID,
			&i.ProviderID,
			&i.ContractID,
			&i.TariffID,
			&i.OriginID,
			&i.DestinationID,
			&i.TransportMode,
			&i.TariffLineItemID,
			&i.ChargeCode,
			&i.Category,
			&i.UnitPriceAmount,
			&i.UnitPriceCurrency,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRatesByShipper = `-- name: ListRatesByShipper :many
SELECT id, shipper_id, name, status, valid_from, valid_to, created_at, updated_at FROM rates WHERE shipper_id = $1 ORDER BY created_at DESC
`

func (q *Queries) ListRatesByShipper(ctx context.Context, shipperID uuid.UUID) ([]Rate, error) {
	rows, err := q.db.Query(ctx, listRatesByShipper, shipperID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Rate
	for rows.Next() {
		var i Rate
		if err := rows.Scan(
			&i.ID,
			&i.ShipperID,
			&i.Name,
			&i.Status,
			&i.ValidFrom,
			&i.ValidTo,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateRate = `-- name: UpdateRate :exec
UPDATE rates SET name = $2, status = $3, valid_from = $4, valid_to = $5, updated_at = $6
WHERE id = $1
`

type UpdateRateParams struct {
	ID        uuid.UUID          `db:"id" json:"id"`
	Name      string             `db:"name" json:"name"`
	Status    RateStatus         `db:"status" json:"status"`
	ValidFrom pgtype.Timestamptz `db:"valid_from" json:"valid_from"`
	ValidTo   pgtype.Timestamptz `db:"valid_to" json:"valid_to"`
	UpdatedAt pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
}

func (q *Queries) UpdateRate(ctx context.Context, arg UpdateRateParams) error {
	_, err := q.db.Exec(ctx, updateRate,
		arg.ID,
		arg.Name,
		arg.Status,
		arg.ValidFrom,
		arg.ValidTo,
		arg.UpdatedAt,
	)
	return err
}
