// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: shipment.sql

package sqlcgen

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
	"github.com/shopspring/decimal"
)

const deleteShipmentItems = `-- name: DeleteShipmentItems :exec
DELETE FROM shipment_items WHERE shipment_id = $1
`

func (q *Queries) DeleteShipmentItems(ctx context.Context, shipmentID uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteShipmentItems, shipmentID)
	return err
}

const deleteShipmentSegments = `-- name: DeleteShipmentSegments :exec
DELETE FROM shipment_planned_route_segments WHERE shipment_id = $1
`

func (q *Queries) DeleteShipmentSegments(ctx context.Context, shipmentID uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteShipmentSegments, shipmentID)
	return err
}

const deleteShipmentTrackingUnits = `-- name: DeleteShipmentTrackingUnits :exec
DELETE FROM shipment_tracking_units WHERE shipment_id = $1
`

func (q *Queries) DeleteShipmentTrackingUnits(ctx context.Context, shipmentID uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteShipmentTrackingUnits, shipmentID)
	return err
}

const getShipmentByID = `-- name: GetShipmentByID :one
SELECT id, shipment_no, shipper_id, consignee_id, status, standard_route_id, rate_id, origin_location_id, dest_location_id, transport_requirements, cost_is_finalized, cost_finalized_at, created_at, updated_at FROM shipments WHERE id = $1
`

func (q *Queries) GetShipmentByID(ctx context.Context, id uuid.UUID) (Shipment, error) {
	row := q.db.QueryRow(ctx, getShipmentByID, id)
	var i Shipment
	err := row.Scan(
		&i.ID,
		&i.ShipmentNo,
		&i.ShipperID,
		&i.ConsigneeID,
		&i.Status,
		&i.StandardRouteID,
		&i.RateID,
		&i.OriginLocationID,
		&i.DestLocationID,
		&i.TransportRequirements,
		&i.CostIsFinalized,
		&i.CostFinalizedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getShipmentByNo = `-- name: GetShipmentByNo :one
SELECT id, shipment_no, shipper_id, consignee_id, status, standard_route_id, rate_id, origin_location_id, dest_location_id, transport_requirements, cost_is_finalized, cost_finalized_at, created_at, updated_at FROM shipments WHERE shipment_no = $1
`

func (q *Queries) GetShipmentByNo(ctx context.Context, shipmentNo string) (Shipment, error) {
	row := q.db.QueryRow(ctx, getShipmentByNo, shipmentNo)
	var i Shipment
	err := row.Scan(
		&i.ID,
		&i.ShipmentNo,
		&i.ShipperID,
		&i.ConsigneeID,
		&i.Status,
		&i.StandardRouteID,
		&i.RateID,
		&i.OriginLocationID,
		&i.DestLocationID,
		&i.TransportRequirements,
		&i.CostIsFinalized,
		&i.CostFinalizedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const insertShipment = `-- name: InsertShipment :exec
INSERT INTO shipments (
    id, shipment_no, shipper_id, consignee_id, status,
    standard_route_id, rate_id, origin_location_id, dest_location_id,
    transport_requirements, cost_is_finalized, cost_finalized_at,
    created_at, updated_at
) VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14)
`

type InsertShipmentParams struct {
	ID                    uuid.UUID          `db:"id" json:"id"`
	ShipmentNo            string             `db:"shipment_no" json:"shipment_no"`
	ShipperID             uuid.UUID          `db:"shipper_id" json:"shipper_id"`
	ConsigneeID           uuid.UUID          `db:"consignee_id" json:"consignee_id"`
	Status                ShipmentStatus     `db:"status" json:"status"`
	StandardRouteID       pgtype.UUID        `db:"standard_route_id" json:"standard_route_id"`
	RateID                pgtype.UUID        `db:"rate_id" json:"rate_id"`
	OriginLocationID      uuid.UUID          `db:"origin_location_id" json:"origin_location_id"`
	DestLocationID        uuid.UUID          `db:"dest_location_id" json:"dest_location_id"`
	TransportRequirements []byte             `db:"transport_requirements" json:"transport_requirements"`
	CostIsFinalized       bool               `db:"cost_is_finalized" json:"cost_is_finalized"`
	CostFinalizedAt       pgtype.Timestamptz `db:"cost_finalized_at" json:"cost_finalized_at"`
	CreatedAt             pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt             pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
}

func (q *Queries) InsertShipment(ctx context.Context, arg InsertShipmentParams) error {
	_, err := q.db.Exec(ctx, insertShipment,
		arg.ID,
		arg.ShipmentNo,
		arg.ShipperID,
		arg.ConsigneeID,
		arg.Status,
		arg.StandardRouteID,
		arg.RateID,
		arg.OriginLocationID,
		arg.DestLocationID,
		arg.TransportRequirements,
		arg.CostIsFinalized,
		arg.CostFinalizedAt,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	return err
}

const insertShipmentItem = `-- name: InsertShipmentItem :exec
INSERT INTO shipment_items (
    id, shipment_id, commodity, hs_code, quantity, weight_kg, volume_m3,
    package_type, loaded_on_tracking_id, attributes
) VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10)
`

type InsertShipmentItemParams struct {
	ID                 uuid.UUID       `db:"id" json:"id"`
	ShipmentID         uuid.UUID       `db:"shipment_id" json:"shipment_id"`
	Commodity          string          `db:"commodity" json:"commodity"`
	HsCode             pgtype.Text     `db:"hs_code" json:"hs_code"`
	Quantity           decimal.Decimal `db:"quantity" json:"quantity"`
	WeightKg           decimal.Decimal `db:"weight_kg" json:"weight_kg"`
	VolumeM3           decimal.Decimal `db:"volume_m3" json:"volume_m3"`
	PackageType        pgtype.Text     `db:"package_type" json:"package_type"`
	LoadedOnTrackingID pgtype.UUID     `db:"loaded_on_tracking_id" json:"loaded_on_tracking_id"`
	Attributes         []byte          `db:"attributes" json:"attributes"`
}

func (q *Queries) InsertShipmentItem(ctx context.Context, arg InsertShipmentItemParams) error {
	_, err := q.db.Exec(ctx, insertShipmentItem,
		arg.ID,
		arg.ShipmentID,
		arg.Commodity,
		arg.HsCode,
		arg.Quantity,
		arg.WeightKg,
		arg.VolumeM3,
		arg.PackageType,
		arg.LoadedOnTrackingID,
		arg.Attributes,
	)
	return err
}

const insertShipmentSegment = `-- name: InsertShipmentSegment :exec
INSERT INTO shipment_planned_route_segments (
    id, shipment_id, sequence_order, origin_location_id, origin_type,
    dest_location_id, dest_type, mode, distance_km, master_lane_id
) VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10)
`

type InsertShipmentSegmentParams struct {
	ID               uuid.UUID      `db:"id" json:"id"`
	ShipmentID       uuid.UUID      `db:"shipment_id" json:"shipment_id"`
	SequenceOrder    int32          `db:"sequence_order" json:"sequence_order"`
	OriginLocationID uuid.UUID      `db:"origin_location_id" json:"origin_location_id"`
	OriginType       LocationType   `db:"origin_type" json:"origin_type"`
	DestLocationID   uuid.UUID      `db:"dest_location_id" json:"dest_location_id"`
	DestType         LocationType   `db:"dest_type" json:"dest_type"`
	Mode             TransportMode  `db:"mode" json:"mode"`
	DistanceKm       pgtype.Numeric `db:"distance_km" json:"distance_km"`
	MasterLaneID     pgtype.UUID    `db:"master_lane_id" json:"master_lane_id"`
}

func (q *Queries) InsertShipmentSegment(ctx context.Context, arg InsertShipmentSegmentParams) error {
	_, err := q.db.Exec(ctx, insertShipmentSegment,
		arg.ID,
		arg.ShipmentID,
		arg.SequenceOrder,
		arg.OriginLocationID,
		arg.OriginType,
		arg.DestLocationID,
		arg.DestType,
		arg.Mode,
		arg.DistanceKm,
		arg.MasterLaneID,
	)
	return err
}

const insertShipmentTrackingUnit = `-- name: InsertShipmentTrackingUnit :exec
INSERT INTO shipment_tracking_units (shipment_id, tracking_unit_id) VALUES ($1, $2)
ON CONFLICT DO NOTHING
`

type InsertShipmentTrackingUnitParams struct {
	ShipmentID     uuid.UUID `db:"shipment_id" json:"shipment_id"`
	TrackingUnitID uuid.UUID `db:"tracking_unit_id" json:"tracking_unit_id"`
}

func (q *Queries) InsertShipmentTrackingUnit(ctx context.Context, arg InsertShipmentTrackingUnitParams) error {
	_, err := q.db.Exec(ctx, insertShipmentTrackingUnit, arg.ShipmentID, arg.TrackingUnitID)
	return err
}

const listShipmentItems = `-- name: ListShipmentItems :many
SELECT id, shipment_id, commodity, hs_code, quantity, weight_kg, volume_m3, package_type, loaded_on_tracking_id, attributes FROM shipment_items WHERE shipment_id = $1
`

func (q *Queries) ListShipmentItems(ctx context.Context, shipmentID uuid.UUID) ([]ShipmentItem, error) {
	rows, err := q.db.Query(ctx, listShipmentItems, shipmentID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ShipmentItem
	for rows.Next() {
		var i ShipmentItem
		if err := rows.Scan(
			&i.ID,
			&i.ShipmentID,
			&i.Commodity,
			&i.HsCode,
			&i.Quantity,
			&i.WeightKg,
			&i.VolumeM3,
			&i.PackageType,
			&i.LoadedOnTrackingID,
			&i.Attributes,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listShipmentSegments = `-- name: ListShipmentSegments :many
SELECT id, shipment_id, sequence_order, origin_location_id, origin_type, dest_location_id, dest_type, mode, distance_km, master_lane_id FROM shipment_planned_route_segments WHERE shipment_id = $1 ORDER BY sequence_order
`

func (q *Queries) ListShipmentSegments(ctx context.Context, shipmentID uuid.UUID) ([]ShipmentPlannedRouteSegment, error) {
	rows, err := q.db.Query(ctx, listShipmentSegments, shipmentID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ShipmentPlannedRouteSegment
	for rows.Next() {
		var i ShipmentPlannedRouteSegment
		if err := rows.Scan(
			&i.ID,
			&i.ShipmentID,
			&i.SequenceOrder,
			&i.OriginLocationID,
			&i.OriginType,
			&i.DestLocationID,
			&i.DestType,
			&i.Mode,
			&i.DistanceKm,
			&i.MasterLaneID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listShipmentTrackingUnitIDs = `-- name: ListShipmentTrackingUnitIDs :many
SELECT tracking_unit_id FROM shipment_tracking_units WHERE shipment_id = $1
`

func (q *Queries) ListShipmentTrackingUnitIDs(ctx context.Context, shipmentID uuid.UUID) ([]uuid.UUID, error) {
	rows, err := q.db.Query(ctx, listShipmentTrackingUnitIDs, shipmentID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []uuid.UUID
	for rows.Next() {
		var tracking_unit_id uuid.UUID
		if err := rows.Scan(&tracking_unit_id); err != nil {
			return nil, err
		}
		items = append(items, tracking_unit_id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateShipment = `-- name: UpdateShipment :exec
UPDATE shipments
SET status = $2, cost_is_finalized = $3, cost_finalized_at = $4, updated_at = $5
WHERE id = $1
`

type UpdateShipmentParams struct {
	ID              uuid.UUID          `db:"id" json:"id"`
	Status          ShipmentStatus     `db:"status" json:"status"`
	CostIsFinalized bool               `db:"cost_is_finalized" json:"cost_is_finalized"`
	CostFinalizedAt pgtype.Timestamptz `db:"cost_finalized_at" json:"cost_finalized_at"`
	UpdatedAt       pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
}

func (q *Queries) UpdateShipment(ctx context.Context, arg UpdateShipmentParams) error {
	_, err := q.db.Exec(ctx, updateShipment,
		arg.ID,
		arg.Status,
		arg.CostIsFinalized,
		arg.CostFinalizedAt,
		arg.UpdatedAt,
	)
	return err
}
