// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: sop_instance.sql

package sqlcgen

import (
	"context"
	"encoding/json"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const getSOPInstanceByID = `-- name: GetSOPInstanceByID :one
SELECT id, shipment_id, definition_id, definition_name, status, created_at, updated_at FROM sop_instances WHERE id = $1
`

func (q *Queries) GetSOPInstanceByID(ctx context.Context, id uuid.UUID) (SopInstance, error) {
	row := q.db.QueryRow(ctx, getSOPInstanceByID, id)
	var i SopInstance
	err := row.Scan(
		&i.ID,
		&i.ShipmentID,
		&i.DefinitionID,
		&i.DefinitionName,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getSOPInstanceByShipmentID = `-- name: GetSOPInstanceByShipmentID :one
SELECT id, shipment_id, definition_id, definition_name, status, created_at, updated_at FROM sop_instances WHERE shipment_id = $1
`

func (q *Queries) GetSOPInstanceByShipmentID(ctx context.Context, shipmentID uuid.UUID) (SopInstance, error) {
	row := q.db.QueryRow(ctx, getSOPInstanceByShipmentID, shipmentID)
	var i SopInstance
	err := row.Scan(
		&i.ID,
		&i.ShipmentID,
		&i.DefinitionID,
		&i.DefinitionName,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const insertSOPInstance = `-- name: InsertSOPInstance :exec
INSERT INTO sop_instances (id, shipment_id, definition_id, definition_name, status, created_at, updated_at)
VALUES ($1, $2, $3, $4, $5, $6, $7)
`

type InsertSOPInstanceParams struct {
	ID             uuid.UUID          `db:"id" json:"id"`
	ShipmentID     uuid.UUID          `db:"shipment_id" json:"shipment_id"`
	DefinitionID   uuid.UUID          `db:"definition_id" json:"definition_id"`
	DefinitionName string             `db:"definition_name" json:"definition_name"`
	Status         SopInstanceStatus  `db:"status" json:"status"`
	CreatedAt      pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt      pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
}

func (q *Queries) InsertSOPInstance(ctx context.Context, arg InsertSOPInstanceParams) error {
	_, err := q.db.Exec(ctx, insertSOPInstance,
		arg.ID,
		arg.ShipmentID,
		arg.DefinitionID,
		arg.DefinitionName,
		arg.Status,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	return err
}

const insertSOPTask = `-- name: InsertSOPTask :exec
INSERT INTO sop_tasks (
    id, sop_instance_id, step_definition_id, name, description,
    order_index, action_type, required_doc_types, generated_doc_type,
    status, assignee_id, linked_document_ids, completed_at, completed_by, note
) VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14, $15)
`

type InsertSOPTaskParams struct {
	ID                uuid.UUID          `db:"id" json:"id"`
	SopInstanceID     uuid.UUID          `db:"sop_instance_id" json:"sop_instance_id"`
	StepDefinitionID  uuid.UUID          `db:"step_definition_id" json:"step_definition_id"`
	Name              string             `db:"name" json:"name"`
	Description       pgtype.Text        `db:"description" json:"description"`
	OrderIndex        int32              `db:"order_index" json:"order_index"`
	ActionType        ActionType         `db:"action_type" json:"action_type"`
	RequiredDocTypes  json.RawMessage    `db:"required_doc_types" json:"required_doc_types"`
	GeneratedDocType  pgtype.Text        `db:"generated_doc_type" json:"generated_doc_type"`
	Status            TaskStatus         `db:"status" json:"status"`
	AssigneeID        pgtype.UUID        `db:"assignee_id" json:"assignee_id"`
	LinkedDocumentIds json.RawMessage    `db:"linked_document_ids" json:"linked_document_ids"`
	CompletedAt       pgtype.Timestamptz `db:"completed_at" json:"completed_at"`
	CompletedBy       pgtype.UUID        `db:"completed_by" json:"completed_by"`
	Note              pgtype.Text        `db:"note" json:"note"`
}

func (q *Queries) InsertSOPTask(ctx context.Context, arg InsertSOPTaskParams) error {
	_, err := q.db.Exec(ctx, insertSOPTask,
		arg.ID,
		arg.SopInstanceID,
		arg.StepDefinitionID,
		arg.Name,
		arg.Description,
		arg.OrderIndex,
		arg.ActionType,
		arg.RequiredDocTypes,
		arg.GeneratedDocType,
		arg.Status,
		arg.AssigneeID,
		arg.LinkedDocumentIds,
		arg.CompletedAt,
		arg.CompletedBy,
		arg.Note,
	)
	return err
}

const listSOPTasksByInstanceID = `-- name: ListSOPTasksByInstanceID :many
SELECT id, sop_instance_id, step_definition_id, name, description, order_index, action_type, required_doc_types, generated_doc_type, status, assignee_id, linked_document_ids, completed_at, completed_by, note FROM sop_tasks WHERE sop_instance_id = $1 ORDER BY order_index
`

func (q *Queries) ListSOPTasksByInstanceID(ctx context.Context, sopInstanceID uuid.UUID) ([]SopTask, error) {
	rows, err := q.db.Query(ctx, listSOPTasksByInstanceID, sopInstanceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SopTask
	for rows.Next() {
		var i SopTask
		if err := rows.Scan(
			&i.ID,
			&i.SopInstanceID,
			&i.StepDefinitionID,
			&i.Name,
			&i.Description,
			&i.OrderIndex,
			&i.ActionType,
			&i.RequiredDocTypes,
			&i.GeneratedDocType,
			&i.Status,
			&i.AssigneeID,
			&i.LinkedDocumentIds,
			&i.CompletedAt,
			&i.CompletedBy,
			&i.Note,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateSOPInstance = `-- name: UpdateSOPInstance :exec
UPDATE sop_instances SET status = $2, updated_at = $3 WHERE id = $1
`

type UpdateSOPInstanceParams struct {
	ID        uuid.UUID          `db:"id" json:"id"`
	Status    SopInstanceStatus  `db:"status" json:"status"`
	UpdatedAt pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
}

func (q *Queries) UpdateSOPInstance(ctx context.Context, arg UpdateSOPInstanceParams) error {
	_, err := q.db.Exec(ctx, updateSOPInstance, arg.ID, arg.Status, arg.UpdatedAt)
	return err
}

const updateSOPTask = `-- name: UpdateSOPTask :exec
UPDATE sop_tasks
SET status = $2, assignee_id = $3, linked_document_ids = $4,
    completed_at = $5, completed_by = $6, note = $7
WHERE id = $1
`

type UpdateSOPTaskParams struct {
	ID                uuid.UUID          `db:"id" json:"id"`
	Status            TaskStatus         `db:"status" json:"status"`
	AssigneeID        pgtype.UUID        `db:"assignee_id" json:"assignee_id"`
	LinkedDocumentIds json.RawMessage    `db:"linked_document_ids" json:"linked_document_ids"`
	CompletedAt       pgtype.Timestamptz `db:"completed_at" json:"completed_at"`
	CompletedBy       pgtype.UUID        `db:"completed_by" json:"completed_by"`
	Note              pgtype.Text        `db:"note" json:"note"`
}

func (q *Queries) UpdateSOPTask(ctx context.Context, arg UpdateSOPTaskParams) error {
	_, err := q.db.Exec(ctx, updateSOPTask,
		arg.ID,
		arg.Status,
		arg.AssigneeID,
		arg.LinkedDocumentIds,
		arg.CompletedAt,
		arg.CompletedBy,
		arg.Note,
	)
	return err
}
