// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: sop_definition.sql

package sqlcgen

import (
	"context"
	"encoding/json"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const deleteSOPStepsByDefinitionID = `-- name: DeleteSOPStepsByDefinitionID :exec
DELETE FROM sop_step_definitions WHERE sop_definition_id = $1
`

func (q *Queries) DeleteSOPStepsByDefinitionID(ctx context.Context, sopDefinitionID uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteSOPStepsByDefinitionID, sopDefinitionID)
	return err
}

const getSOPDefinitionByID = `-- name: GetSOPDefinitionByID :one
SELECT id, name, description, direction, transport_mode, origin_country, dest_country, status, version, created_at, updated_at FROM sop_definitions WHERE id = $1
`

func (q *Queries) GetSOPDefinitionByID(ctx context.Context, id uuid.UUID) (SopDefinition, error) {
	row := q.db.QueryRow(ctx, getSOPDefinitionByID, id)
	var i SopDefinition
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.Direction,
		&i.TransportMode,
		&i.OriginCountry,
		&i.DestCountry,
		&i.Status,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const insertSOPDefinition = `-- name: InsertSOPDefinition :exec
INSERT INTO sop_definitions (
    id, name, description, direction, transport_mode,
    origin_country, dest_country, status, version, created_at, updated_at
) VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11)
`

type InsertSOPDefinitionParams struct {
	ID            uuid.UUID           `db:"id" json:"id"`
	Name          string              `db:"name" json:"name"`
	Description   pgtype.Text         `db:"description" json:"description"`
	Direction     string              `db:"direction" json:"direction"`
	TransportMode TransportMode       `db:"transport_mode" json:"transport_mode"`
	OriginCountry pgtype.Text         `db:"origin_country" json:"origin_country"`
	DestCountry   pgtype.Text         `db:"dest_country" json:"dest_country"`
	Status        SopDefinitionStatus `db:"status" json:"status"`
	Version       int32               `db:"version" json:"version"`
	CreatedAt     pgtype.Timestamptz  `db:"created_at" json:"created_at"`
	UpdatedAt     pgtype.Timestamptz  `db:"updated_at" json:"updated_at"`
}

func (q *Queries) InsertSOPDefinition(ctx context.Context, arg InsertSOPDefinitionParams) error {
	_, err := q.db.Exec(ctx, insertSOPDefinition,
		arg.ID,
		arg.Name,
		arg.Description,
		arg.Direction,
		arg.TransportMode,
		arg.OriginCountry,
		arg.DestCountry,
		arg.Status,
		arg.Version,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	return err
}

const insertSOPStep = `-- name: InsertSOPStep :exec
INSERT INTO sop_step_definitions (
    id, sop_definition_id, name, description, order_index,
    required_doc_types, generated_doc_type, action_type, is_automatable
) VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9)
`

type InsertSOPStepParams struct {
	ID               uuid.UUID       `db:"id" json:"id"`
	SopDefinitionID  uuid.UUID       `db:"sop_definition_id" json:"sop_definition_id"`
	Name             string          `db:"name" json:"name"`
	Description      pgtype.Text     `db:"description" json:"description"`
	OrderIndex       int32           `db:"order_index" json:"order_index"`
	RequiredDocTypes json.RawMessage `db:"required_doc_types" json:"required_doc_types"`
	GeneratedDocType pgtype.Text     `db:"generated_doc_type" json:"generated_doc_type"`
	ActionType       ActionType      `db:"action_type" json:"action_type"`
	IsAutomatable    bool            `db:"is_automatable" json:"is_automatable"`
}

func (q *Queries) InsertSOPStep(ctx context.Context, arg InsertSOPStepParams) error {
	_, err := q.db.Exec(ctx, insertSOPStep,
		arg.ID,
		arg.SopDefinitionID,
		arg.Name,
		arg.Description,
		arg.OrderIndex,
		arg.RequiredDocTypes,
		arg.GeneratedDocType,
		arg.ActionType,
		arg.IsAutomatable,
	)
	return err
}

const listActiveSOPDefinitions = `-- name: ListActiveSOPDefinitions :many
SELECT id, name, description, direction, transport_mode, origin_country, dest_country, status, version, created_at, updated_at FROM sop_definitions WHERE status = 'ACTIVE' ORDER BY name
`

func (q *Queries) ListActiveSOPDefinitions(ctx context.Context) ([]SopDefinition, error) {
	rows, err := q.db.Query(ctx, listActiveSOPDefinitions)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SopDefinition
	for rows.Next() {
		var i SopDefinition
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.Direction,
			&i.TransportMode,
			&i.OriginCountry,
			&i.DestCountry,
			&i.Status,
			&i.Version,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listActiveSOPDefinitionsByScope = `-- name: ListActiveSOPDefinitionsByScope :many
SELECT id, name, description, direction, transport_mode, origin_country, dest_country, status, version, created_at, updated_at FROM sop_definitions
WHERE status = 'ACTIVE'
  AND direction = $1
  AND transport_mode = $2
  AND (origin_country IS NULL OR origin_country = $3)
  AND (dest_country IS NULL OR dest_country = $4)
ORDER BY name
`

type ListActiveSOPDefinitionsByScopeParams struct {
	Direction     string        `db:"direction" json:"direction"`
	TransportMode TransportMode `db:"transport_mode" json:"transport_mode"`
	OriginCountry pgtype.Text   `db:"origin_country" json:"origin_country"`
	DestCountry   pgtype.Text   `db:"dest_country" json:"dest_country"`
}

func (q *Queries) ListActiveSOPDefinitionsByScope(ctx context.Context, arg ListActiveSOPDefinitionsByScopeParams) ([]SopDefinition, error) {
	rows, err := q.db.Query(ctx, listActiveSOPDefinitionsByScope,
		arg.Direction,
		arg.TransportMode,
		arg.OriginCountry,
		arg.DestCountry,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SopDefinition
	for rows.Next() {
		var i SopDefinition
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.Direction,
			&i.TransportMode,
			&i.OriginCountry,
			&i.DestCountry,
			&i.Status,
			&i.Version,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSOPStepsByDefinitionID = `-- name: ListSOPStepsByDefinitionID :many
SELECT id, sop_definition_id, name, description, order_index, required_doc_types, generated_doc_type, action_type, is_automatable FROM sop_step_definitions WHERE sop_definition_id = $1 ORDER BY order_index
`

func (q *Queries) ListSOPStepsByDefinitionID(ctx context.Context, sopDefinitionID uuid.UUID) ([]SopStepDefinition, error) {
	rows, err := q.db.Query(ctx, listSOPStepsByDefinitionID, sopDefinitionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SopStepDefinition
	for rows.Next() {
		var i SopStepDefinition
		if err := rows.Scan(
			&i.ID,
			&i.SopDefinitionID,
			&i.Name,
			&i.Description,
			&i.OrderIndex,
			&i.RequiredDocTypes,
			&i.GeneratedDocType,
			&i.ActionType,
			&i.IsAutomatable,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateSOPDefinition = `-- name: UpdateSOPDefinition :exec
UPDATE sop_definitions
SET name = $2, description = $3, status = $4, version = $5, updated_at = $6
WHERE id = $1
`

type UpdateSOPDefinitionParams struct {
	ID          uuid.UUID           `db:"id" json:"id"`
	Name        string              `db:"name" json:"name"`
	Description pgtype.Text         `db:"description" json:"description"`
	Status      SopDefinitionStatus `db:"status" json:"status"`
	Version     int32               `db:"version" json:"version"`
	UpdatedAt   pgtype.Timestamptz  `db:"updated_at" json:"updated_at"`
}

func (q *Queries) UpdateSOPDefinition(ctx context.Context, arg UpdateSOPDefinitionParams) error {
	_, err := q.db.Exec(ctx, updateSOPDefinition,
		arg.ID,
		arg.Name,
		arg.Description,
		arg.Status,
		arg.Version,
		arg.UpdatedAt,
	)
	return err
}
