// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: standard_route.sql

package sqlcgen

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const deleteStandardRouteLegsByRouteID = `-- name: DeleteStandardRouteLegsByRouteID :exec
DELETE FROM standard_route_legs WHERE standard_route_id = $1
`

func (q *Queries) DeleteStandardRouteLegsByRouteID(ctx context.Context, standardRouteID uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteStandardRouteLegsByRouteID, standardRouteID)
	return err
}

const getStandardRouteByID = `-- name: GetStandardRouteByID :one
SELECT id, name, shipper_id, origin_location_id, destination_location_id, status, standard_lead_time_days, target_cost_amount, target_cost_currency, valid_from, valid_to, created_at, updated_at FROM standard_routes WHERE id = $1
`

func (q *Queries) GetStandardRouteByID(ctx context.Context, id uuid.UUID) (StandardRoute, error) {
	row := q.db.QueryRow(ctx, getStandardRouteByID, id)
	var i StandardRoute
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.ShipperID,
		&i.OriginLocationID,
		&i.DestinationLocationID,
		&i.Status,
		&i.StandardLeadTimeDays,
		&i.TargetCostAmount,
		&i.TargetCostCurrency,
		&i.ValidFrom,
		&i.ValidTo,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const insertStandardRoute = `-- name: InsertStandardRoute :exec
INSERT INTO standard_routes (
    id, name, shipper_id, origin_location_id, destination_location_id,
    status, standard_lead_time_days, target_cost_amount, target_cost_currency,
    valid_from, valid_to, created_at, updated_at
) VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13)
`

type InsertStandardRouteParams struct {
	ID                    uuid.UUID           `db:"id" json:"id"`
	Name                  string              `db:"name" json:"name"`
	ShipperID             uuid.UUID           `db:"shipper_id" json:"shipper_id"`
	OriginLocationID      uuid.UUID           `db:"origin_location_id" json:"origin_location_id"`
	DestinationLocationID uuid.UUID           `db:"destination_location_id" json:"destination_location_id"`
	Status                StandardRouteStatus `db:"status" json:"status"`
	StandardLeadTimeDays  int32               `db:"standard_lead_time_days" json:"standard_lead_time_days"`
	TargetCostAmount      pgtype.Numeric      `db:"target_cost_amount" json:"target_cost_amount"`
	TargetCostCurrency    pgtype.Text         `db:"target_cost_currency" json:"target_cost_currency"`
	ValidFrom             pgtype.Timestamptz  `db:"valid_from" json:"valid_from"`
	ValidTo               pgtype.Timestamptz  `db:"valid_to" json:"valid_to"`
	CreatedAt             pgtype.Timestamptz  `db:"created_at" json:"created_at"`
	UpdatedAt             pgtype.Timestamptz  `db:"updated_at" json:"updated_at"`
}

func (q *Queries) InsertStandardRoute(ctx context.Context, arg InsertStandardRouteParams) error {
	_, err := q.db.Exec(ctx, insertStandardRoute,
		arg.ID,
		arg.Name,
		arg.ShipperID,
		arg.OriginLocationID,
		arg.DestinationLocationID,
		arg.Status,
		arg.StandardLeadTimeDays,
		arg.TargetCostAmount,
		arg.TargetCostCurrency,
		arg.ValidFrom,
		arg.ValidTo,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	return err
}

const insertStandardRouteLeg = `-- name: InsertStandardRouteLeg :exec
INSERT INTO standard_route_legs (
    id, standard_route_id, sequence_order, origin_location_id, dest_location_id,
    target_mode, standard_transit_days, master_lane_id
) VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
`

type InsertStandardRouteLegParams struct {
	ID                  uuid.UUID     `db:"id" json:"id"`
	StandardRouteID     uuid.UUID     `db:"standard_route_id" json:"standard_route_id"`
	SequenceOrder       int32         `db:"sequence_order" json:"sequence_order"`
	OriginLocationID    uuid.UUID     `db:"origin_location_id" json:"origin_location_id"`
	DestLocationID      uuid.UUID     `db:"dest_location_id" json:"dest_location_id"`
	TargetMode          TransportMode `db:"target_mode" json:"target_mode"`
	StandardTransitDays int32         `db:"standard_transit_days" json:"standard_transit_days"`
	MasterLaneID        pgtype.UUID   `db:"master_lane_id" json:"master_lane_id"`
}

func (q *Queries) InsertStandardRouteLeg(ctx context.Context, arg InsertStandardRouteLegParams) error {
	_, err := q.db.Exec(ctx, insertStandardRouteLeg,
		arg.ID,
		arg.StandardRouteID,
		arg.SequenceOrder,
		arg.OriginLocationID,
		arg.DestLocationID,
		arg.TargetMode,
		arg.StandardTransitDays,
		arg.MasterLaneID,
	)
	return err
}

const listActiveStandardRoutesByShipper = `-- name: ListActiveStandardRoutesByShipper :many
SELECT id, name, shipper_id, origin_location_id, destination_location_id, status, standard_lead_time_days, target_cost_amount, target_cost_currency, valid_from, valid_to, created_at, updated_at FROM standard_routes WHERE shipper_id = $1 AND status = 'ACTIVE' ORDER BY name
`

func (q *Queries) ListActiveStandardRoutesByShipper(ctx context.Context, shipperID uuid.UUID) ([]StandardRoute, error) {
	rows, err := q.db.Query(ctx, listActiveStandardRoutesByShipper, shipperID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []StandardRoute
	for rows.Next() {
		var i StandardRoute
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.ShipperID,
			&i.OriginLocationID,
			&i.DestinationLocationID,
			&i.Status,
			&i.StandardLeadTimeDays,
			&i.TargetCostAmount,
			&i.TargetCostCurrency,
			&i.ValidFrom,
			&i.ValidTo,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listStandardRouteLegsByRouteID = `-- name: ListStandardRouteLegsByRouteID :many
SELECT id, standard_route_id, sequence_order, origin_location_id, dest_location_id, target_mode, standard_transit_days, master_lane_id FROM standard_route_legs WHERE standard_route_id = $1 ORDER BY sequence_order
`

func (q *Queries) ListStandardRouteLegsByRouteID(ctx context.Context, standardRouteID uuid.UUID) ([]StandardRouteLeg, error) {
	rows, err := q.db.Query(ctx, listStandardRouteLegsByRouteID, standardRouteID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []StandardRouteLeg
	for rows.Next() {
		var i StandardRouteLeg
		if err := rows.Scan(
			&i.ID,
			&i.StandardRouteID,
			&i.SequenceOrder,
			&i.OriginLocationID,
			&i.DestLocationID,
			&i.TargetMode,
			&i.StandardTransitDays,
			&i.MasterLaneID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateStandardRoute = `-- name: UpdateStandardRoute :exec
UPDATE standard_routes
SET name = $2, status = $3, standard_lead_time_days = $4,
    target_cost_amount = $5, target_cost_currency = $6,
    valid_from = $7, valid_to = $8, updated_at = $9
WHERE id = $1
`

type UpdateStandardRouteParams struct {
	ID                   uuid.UUID           `db:"id" json:"id"`
	Name                 string              `db:"name" json:"name"`
	Status               StandardRouteStatus `db:"status" json:"status"`
	StandardLeadTimeDays int32               `db:"standard_lead_time_days" json:"standard_lead_time_days"`
	TargetCostAmount     pgtype.Numeric      `db:"target_cost_amount" json:"target_cost_amount"`
	TargetCostCurrency   pgtype.Text         `db:"target_cost_currency" json:"target_cost_currency"`
	ValidFrom            pgtype.Timestamptz  `db:"valid_from" json:"valid_from"`
	ValidTo              pgtype.Timestamptz  `db:"valid_to" json:"valid_to"`
	UpdatedAt            pgtype.Timestamptz  `db:"updated_at" json:"updated_at"`
}

func (q *Queries) UpdateStandardRoute(ctx context.Context, arg UpdateStandardRouteParams) error {
	_, err := q.db.Exec(ctx, updateStandardRoute,
		arg.ID,
		arg.Name,
		arg.Status,
		arg.StandardLeadTimeDays,
		arg.TargetCostAmount,
		arg.TargetCostCurrency,
		arg.ValidFrom,
		arg.ValidTo,
		arg.UpdatedAt,
	)
	return err
}
