// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: tariff.sql

package sqlcgen

import (
	"context"
	"encoding/json"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const countTariffsByContractID = `-- name: CountTariffsByContractID :one
SELECT COUNT(*) FROM tariffs WHERE contract_id = $1
`

func (q *Queries) CountTariffsByContractID(ctx context.Context, contractID uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countTariffsByContractID, contractID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const deleteTariff = `-- name: DeleteTariff :exec
DELETE FROM tariffs WHERE id = $1
`

func (q *Queries) DeleteTariff(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteTariff, id)
	return err
}

const deleteTariffLineItemsByTariffID = `-- name: DeleteTariffLineItemsByTariffID :exec
DELETE FROM tariff_line_items WHERE tariff_id = $1
`

func (q *Queries) DeleteTariffLineItemsByTariffID(ctx context.Context, tariffID uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteTariffLineItemsByTariffID, tariffID)
	return err
}

const getLatestTariffVersionByContractIDAndName = `-- name: GetLatestTariffVersionByContractIDAndName :one
SELECT id, contract_id, name, version, base_version_id, effective_from, effective_to, created_at, updated_at FROM tariffs WHERE contract_id = $1 AND name = $2 ORDER BY version DESC LIMIT 1
`

type GetLatestTariffVersionByContractIDAndNameParams struct {
	ContractID uuid.UUID `db:"contract_id" json:"contract_id"`
	Name       string    `db:"name" json:"name"`
}

func (q *Queries) GetLatestTariffVersionByContractIDAndName(ctx context.Context, arg GetLatestTariffVersionByContractIDAndNameParams) (Tariff, error) {
	row := q.db.QueryRow(ctx, getLatestTariffVersionByContractIDAndName, arg.ContractID, arg.Name)
	var i Tariff
	err := row.Scan(
		&i.ID,
		&i.ContractID,
		&i.Name,
		&i.Version,
		&i.BaseVersionID,
		&i.EffectiveFrom,
		&i.EffectiveTo,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getTariffByID = `-- name: GetTariffByID :one
SELECT id, contract_id, name, version, base_version_id, effective_from, effective_to, created_at, updated_at FROM tariffs WHERE id = $1
`

func (q *Queries) GetTariffByID(ctx context.Context, id uuid.UUID) (Tariff, error) {
	row := q.db.QueryRow(ctx, getTariffByID, id)
	var i Tariff
	err := row.Scan(
		&i.ID,
		&i.ContractID,
		&i.Name,
		&i.Version,
		&i.BaseVersionID,
		&i.EffectiveFrom,
		&i.EffectiveTo,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const insertTariff = `-- name: InsertTariff :exec
INSERT INTO tariffs (id, contract_id, name, version, base_version_id, effective_from, effective_to, created_at, updated_at)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9)
`

type InsertTariffParams struct {
	ID            uuid.UUID          `db:"id" json:"id"`
	ContractID    uuid.UUID          `db:"contract_id" json:"contract_id"`
	Name          string             `db:"name" json:"name"`
	Version       int32              `db:"version" json:"version"`
	BaseVersionID pgtype.UUID        `db:"base_version_id" json:"base_version_id"`
	EffectiveFrom pgtype.Timestamptz `db:"effective_from" json:"effective_from"`
	EffectiveTo   pgtype.Timestamptz `db:"effective_to" json:"effective_to"`
	CreatedAt     pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt     pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
}

func (q *Queries) InsertTariff(ctx context.Context, arg InsertTariffParams) error {
	_, err := q.db.Exec(ctx, insertTariff,
		arg.ID,
		arg.ContractID,
		arg.Name,
		arg.Version,
		arg.BaseVersionID,
		arg.EffectiveFrom,
		arg.EffectiveTo,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	return err
}

const insertTariffLineItem = `-- name: InsertTariffLineItem :exec
INSERT INTO tariff_line_items (id, tariff_id, charge_code, category, scope, logic, created_at)
VALUES ($1, $2, $3, $4, $5, $6, $7)
`

type InsertTariffLineItemParams struct {
	ID         uuid.UUID          `db:"id" json:"id"`
	TariffID   uuid.UUID          `db:"tariff_id" json:"tariff_id"`
	ChargeCode string             `db:"charge_code" json:"charge_code"`
	Category   string             `db:"category" json:"category"`
	Scope      json.RawMessage    `db:"scope" json:"scope"`
	Logic      json.RawMessage    `db:"logic" json:"logic"`
	CreatedAt  pgtype.Timestamptz `db:"created_at" json:"created_at"`
}

func (q *Queries) InsertTariffLineItem(ctx context.Context, arg InsertTariffLineItemParams) error {
	_, err := q.db.Exec(ctx, insertTariffLineItem,
		arg.ID,
		arg.TariffID,
		arg.ChargeCode,
		arg.Category,
		arg.Scope,
		arg.Logic,
		arg.CreatedAt,
	)
	return err
}

const listTariffLineItemsByTariffID = `-- name: ListTariffLineItemsByTariffID :many
SELECT id, tariff_id, charge_code, category, scope, logic, created_at FROM tariff_line_items WHERE tariff_id = $1
`

func (q *Queries) ListTariffLineItemsByTariffID(ctx context.Context, tariffID uuid.UUID) ([]TariffLineItem, error) {
	rows, err := q.db.Query(ctx, listTariffLineItemsByTariffID, tariffID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []TariffLineItem
	for rows.Next() {
		var i TariffLineItem
		if err := rows.Scan(
			&i.ID,
			&i.TariffID,
			&i.ChargeCode,
			&i.Category,
			&i.Scope,
			&i.Logic,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTariffsByContractID = `-- name: ListTariffsByContractID :many
SELECT id, contract_id, name, version, base_version_id, effective_from, effective_to, created_at, updated_at FROM tariffs WHERE contract_id = $1 ORDER BY name, version
`

func (q *Queries) ListTariffsByContractID(ctx context.Context, contractID uuid.UUID) ([]Tariff, error) {
	rows, err := q.db.Query(ctx, listTariffsByContractID, contractID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Tariff
	for rows.Next() {
		var i Tariff
		if err := rows.Scan(
			&i.ID,
			&i.ContractID,
			&i.Name,
			&i.Version,
			&i.BaseVersionID,
			&i.EffectiveFrom,
			&i.EffectiveTo,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTariffsByContractIDAndName = `-- name: ListTariffsByContractIDAndName :many
SELECT id, contract_id, name, version, base_version_id, effective_from, effective_to, created_at, updated_at FROM tariffs WHERE contract_id = $1 AND name = $2 ORDER BY version
`

type ListTariffsByContractIDAndNameParams struct {
	ContractID uuid.UUID `db:"contract_id" json:"contract_id"`
	Name       string    `db:"name" json:"name"`
}

func (q *Queries) ListTariffsByContractIDAndName(ctx context.Context, arg ListTariffsByContractIDAndNameParams) ([]Tariff, error) {
	rows, err := q.db.Query(ctx, listTariffsByContractIDAndName, arg.ContractID, arg.Name)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Tariff
	for rows.Next() {
		var i Tariff
		if err := rows.Scan(
			&i.ID,
			&i.ContractID,
			&i.Name,
			&i.Version,
			&i.BaseVersionID,
			&i.EffectiveFrom,
			&i.EffectiveTo,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateTariff = `-- name: UpdateTariff :exec
UPDATE tariffs
SET name = $2, version = $3, base_version_id = $4,
    effective_from = $5, effective_to = $6, updated_at = $7
WHERE id = $1
`

type UpdateTariffParams struct {
	ID            uuid.UUID          `db:"id" json:"id"`
	Name          string             `db:"name" json:"name"`
	Version       int32              `db:"version" json:"version"`
	BaseVersionID pgtype.UUID        `db:"base_version_id" json:"base_version_id"`
	EffectiveFrom pgtype.Timestamptz `db:"effective_from" json:"effective_from"`
	EffectiveTo   pgtype.Timestamptz `db:"effective_to" json:"effective_to"`
	UpdatedAt     pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
}

func (q *Queries) UpdateTariff(ctx context.Context, arg UpdateTariffParams) error {
	_, err := q.db.Exec(ctx, updateTariff,
		arg.ID,
		arg.Name,
		arg.Version,
		arg.BaseVersionID,
		arg.EffectiveFrom,
		arg.EffectiveTo,
		arg.UpdatedAt,
	)
	return err
}
