// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: tracking.sql

package sqlcgen

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const deleteTrackingSegmentsByUnitID = `-- name: DeleteTrackingSegmentsByUnitID :exec
DELETE FROM tracking_segments WHERE tracking_unit_id = $1
`

func (q *Queries) DeleteTrackingSegmentsByUnitID(ctx context.Context, trackingUnitID uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteTrackingSegmentsByUnitID, trackingUnitID)
	return err
}

const getTrackingUnitByID = `-- name: GetTrackingUnitByID :one
SELECT id, tracking_number, tracking_number_type, carrier_id, current_status, last_updated FROM tracking_units WHERE id = $1
`

func (q *Queries) GetTrackingUnitByID(ctx context.Context, id uuid.UUID) (TrackingUnit, error) {
	row := q.db.QueryRow(ctx, getTrackingUnitByID, id)
	var i TrackingUnit
	err := row.Scan(
		&i.ID,
		&i.TrackingNumber,
		&i.TrackingNumberType,
		&i.CarrierID,
		&i.CurrentStatus,
		&i.LastUpdated,
	)
	return i, err
}

const getTrackingUnitByNumber = `-- name: GetTrackingUnitByNumber :one
SELECT id, tracking_number, tracking_number_type, carrier_id, current_status, last_updated FROM tracking_units WHERE tracking_number = $1
`

func (q *Queries) GetTrackingUnitByNumber(ctx context.Context, trackingNumber string) (TrackingUnit, error) {
	row := q.db.QueryRow(ctx, getTrackingUnitByNumber, trackingNumber)
	var i TrackingUnit
	err := row.Scan(
		&i.ID,
		&i.TrackingNumber,
		&i.TrackingNumberType,
		&i.CarrierID,
		&i.CurrentStatus,
		&i.LastUpdated,
	)
	return i, err
}

const insertTrackingEvent = `-- name: InsertTrackingEvent :exec
INSERT INTO tracking_events (id, segment_id, timestamp, source, code, description, location_raw, raw_payload)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
`

type InsertTrackingEventParams struct {
	ID          uuid.UUID          `db:"id" json:"id"`
	SegmentID   uuid.UUID          `db:"segment_id" json:"segment_id"`
	Timestamp   pgtype.Timestamptz `db:"timestamp" json:"timestamp"`
	Source      TrackingSourceType `db:"source" json:"source"`
	Code        string             `db:"code" json:"code"`
	Description pgtype.Text        `db:"description" json:"description"`
	LocationRaw pgtype.Text        `db:"location_raw" json:"location_raw"`
	RawPayload  pgtype.Text        `db:"raw_payload" json:"raw_payload"`
}

func (q *Queries) InsertTrackingEvent(ctx context.Context, arg InsertTrackingEventParams) error {
	_, err := q.db.Exec(ctx, insertTrackingEvent,
		arg.ID,
		arg.SegmentID,
		arg.Timestamp,
		arg.Source,
		arg.Code,
		arg.Description,
		arg.LocationRaw,
		arg.RawPayload,
	)
	return err
}

const insertTrackingSegment = `-- name: InsertTrackingSegment :exec
INSERT INTO tracking_segments (
    id, tracking_unit_id, actual_origin_location_id, actual_dest_location_id,
    mode, carrier_tracking_number, primary_source, status,
    actual_departure, actual_arrival, estimated_arrival
) VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11)
`

type InsertTrackingSegmentParams struct {
	ID                     uuid.UUID          `db:"id" json:"id"`
	TrackingUnitID         uuid.UUID          `db:"tracking_unit_id" json:"tracking_unit_id"`
	ActualOriginLocationID uuid.UUID          `db:"actual_origin_location_id" json:"actual_origin_location_id"`
	ActualDestLocationID   uuid.UUID          `db:"actual_dest_location_id" json:"actual_dest_location_id"`
	Mode                   TransportMode      `db:"mode" json:"mode"`
	CarrierTrackingNumber  pgtype.Text        `db:"carrier_tracking_number" json:"carrier_tracking_number"`
	PrimarySource          TrackingSourceType `db:"primary_source" json:"primary_source"`
	Status                 TrackingStatus     `db:"status" json:"status"`
	ActualDeparture        pgtype.Timestamptz `db:"actual_departure" json:"actual_departure"`
	ActualArrival          pgtype.Timestamptz `db:"actual_arrival" json:"actual_arrival"`
	EstimatedArrival       pgtype.Timestamptz `db:"estimated_arrival" json:"estimated_arrival"`
}

func (q *Queries) InsertTrackingSegment(ctx context.Context, arg InsertTrackingSegmentParams) error {
	_, err := q.db.Exec(ctx, insertTrackingSegment,
		arg.ID,
		arg.TrackingUnitID,
		arg.ActualOriginLocationID,
		arg.ActualDestLocationID,
		arg.Mode,
		arg.CarrierTrackingNumber,
		arg.PrimarySource,
		arg.Status,
		arg.ActualDeparture,
		arg.ActualArrival,
		arg.EstimatedArrival,
	)
	return err
}

const insertTrackingUnit = `-- name: InsertTrackingUnit :exec
INSERT INTO tracking_units (id, tracking_number, tracking_number_type, carrier_id, current_status, last_updated)
VALUES ($1, $2, $3, $4, $5, $6)
`

type InsertTrackingUnitParams struct {
	ID                 uuid.UUID          `db:"id" json:"id"`
	TrackingNumber     string             `db:"tracking_number" json:"tracking_number"`
	TrackingNumberType TrackingNumberType `db:"tracking_number_type" json:"tracking_number_type"`
	CarrierID          uuid.UUID          `db:"carrier_id" json:"carrier_id"`
	CurrentStatus      TrackingStatus     `db:"current_status" json:"current_status"`
	LastUpdated        pgtype.Timestamptz `db:"last_updated" json:"last_updated"`
}

func (q *Queries) InsertTrackingUnit(ctx context.Context, arg InsertTrackingUnitParams) error {
	_, err := q.db.Exec(ctx, insertTrackingUnit,
		arg.ID,
		arg.TrackingNumber,
		arg.TrackingNumberType,
		arg.CarrierID,
		arg.CurrentStatus,
		arg.LastUpdated,
	)
	return err
}

const listTrackingEventsBySegmentID = `-- name: ListTrackingEventsBySegmentID :many
SELECT id, segment_id, timestamp, source, code, description, location_raw, raw_payload FROM tracking_events WHERE segment_id = $1 ORDER BY timestamp
`

func (q *Queries) ListTrackingEventsBySegmentID(ctx context.Context, segmentID uuid.UUID) ([]TrackingEvent, error) {
	rows, err := q.db.Query(ctx, listTrackingEventsBySegmentID, segmentID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []TrackingEvent
	for rows.Next() {
		var i TrackingEvent
		if err := rows.Scan(
			&i.ID,
			&i.SegmentID,
			&i.Timestamp,
			&i.Source,
			&i.Code,
			&i.Description,
			&i.LocationRaw,
			&i.RawPayload,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTrackingSegmentsByUnitID = `-- name: ListTrackingSegmentsByUnitID :many
SELECT id, tracking_unit_id, actual_origin_location_id, actual_dest_location_id, mode, carrier_tracking_number, primary_source, status, actual_departure, actual_arrival, estimated_arrival FROM tracking_segments WHERE tracking_unit_id = $1
`

func (q *Queries) ListTrackingSegmentsByUnitID(ctx context.Context, trackingUnitID uuid.UUID) ([]TrackingSegment, error) {
	rows, err := q.db.Query(ctx, listTrackingSegmentsByUnitID, trackingUnitID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []TrackingSegment
	for rows.Next() {
		var i TrackingSegment
		if err := rows.Scan(
			&i.ID,
			&i.TrackingUnitID,
			&i.ActualOriginLocationID,
			&i.ActualDestLocationID,
			&i.Mode,
			&i.CarrierTrackingNumber,
			&i.PrimarySource,
			&i.Status,
			&i.ActualDeparture,
			&i.ActualArrival,
			&i.EstimatedArrival,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateTrackingSegment = `-- name: UpdateTrackingSegment :exec
UPDATE tracking_segments
SET status = $2, actual_departure = $3, actual_arrival = $4, estimated_arrival = $5
WHERE id = $1
`

type UpdateTrackingSegmentParams struct {
	ID               uuid.UUID          `db:"id" json:"id"`
	Status           TrackingStatus     `db:"status" json:"status"`
	ActualDeparture  pgtype.Timestamptz `db:"actual_departure" json:"actual_departure"`
	ActualArrival    pgtype.Timestamptz `db:"actual_arrival" json:"actual_arrival"`
	EstimatedArrival pgtype.Timestamptz `db:"estimated_arrival" json:"estimated_arrival"`
}

func (q *Queries) UpdateTrackingSegment(ctx context.Context, arg UpdateTrackingSegmentParams) error {
	_, err := q.db.Exec(ctx, updateTrackingSegment,
		arg.ID,
		arg.Status,
		arg.ActualDeparture,
		arg.ActualArrival,
		arg.EstimatedArrival,
	)
	return err
}

const updateTrackingUnit = `-- name: UpdateTrackingUnit :exec
UPDATE tracking_units SET current_status = $2, last_updated = $3 WHERE id = $1
`

type UpdateTrackingUnitParams struct {
	ID            uuid.UUID          `db:"id" json:"id"`
	CurrentStatus TrackingStatus     `db:"current_status" json:"current_status"`
	LastUpdated   pgtype.Timestamptz `db:"last_updated" json:"last_updated"`
}

func (q *Queries) UpdateTrackingUnit(ctx context.Context, arg UpdateTrackingUnitParams) error {
	_, err := q.db.Exec(ctx, updateTrackingUnit, arg.ID, arg.CurrentStatus, arg.LastUpdated)
	return err
}
