// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: vendor.sql

package sqlcgen

import (
	"context"
	"encoding/json"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const getVendorByID = `-- name: GetVendorByID :one
SELECT id, name, type, credit_rating, payment_days, payment_currency, preferred_vendor, capabilities, contacts, created_at, updated_at FROM vendors WHERE id = $1
`

func (q *Queries) GetVendorByID(ctx context.Context, id uuid.UUID) (Vendor, error) {
	row := q.db.QueryRow(ctx, getVendorByID, id)
	var i Vendor
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Type,
		&i.CreditRating,
		&i.PaymentDays,
		&i.PaymentCurrency,
		&i.PreferredVendor,
		&i.Capabilities,
		&i.Contacts,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const insertVendor = `-- name: InsertVendor :exec
INSERT INTO vendors (
    id, name, type, credit_rating, payment_days, payment_currency,
    preferred_vendor, capabilities, contacts, created_at, updated_at
) VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11)
`

type InsertVendorParams struct {
	ID              uuid.UUID          `db:"id" json:"id"`
	Name            string             `db:"name" json:"name"`
	Type            ProviderType       `db:"type" json:"type"`
	CreditRating    string             `db:"credit_rating" json:"credit_rating"`
	PaymentDays     int32              `db:"payment_days" json:"payment_days"`
	PaymentCurrency string             `db:"payment_currency" json:"payment_currency"`
	PreferredVendor bool               `db:"preferred_vendor" json:"preferred_vendor"`
	Capabilities    json.RawMessage    `db:"capabilities" json:"capabilities"`
	Contacts        json.RawMessage    `db:"contacts" json:"contacts"`
	CreatedAt       pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt       pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
}

func (q *Queries) InsertVendor(ctx context.Context, arg InsertVendorParams) error {
	_, err := q.db.Exec(ctx, insertVendor,
		arg.ID,
		arg.Name,
		arg.Type,
		arg.CreditRating,
		arg.PaymentDays,
		arg.PaymentCurrency,
		arg.PreferredVendor,
		arg.Capabilities,
		arg.Contacts,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	return err
}

const listVendorsByName = `-- name: ListVendorsByName :many
SELECT id, name, type, credit_rating, payment_days, payment_currency, preferred_vendor, capabilities, contacts, created_at, updated_at FROM vendors WHERE name ILIKE '%' || $1 || '%' ORDER BY name
`

func (q *Queries) ListVendorsByName(ctx context.Context, dollar_1 pgtype.Text) ([]Vendor, error) {
	rows, err := q.db.Query(ctx, listVendorsByName, dollar_1)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Vendor
	for rows.Next() {
		var i Vendor
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Type,
			&i.CreditRating,
			&i.PaymentDays,
			&i.PaymentCurrency,
			&i.PreferredVendor,
			&i.Capabilities,
			&i.Contacts,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateVendor = `-- name: UpdateVendor :exec
UPDATE vendors
SET name = $2, type = $3, credit_rating = $4, payment_days = $5,
    payment_currency = $6, preferred_vendor = $7, capabilities = $8,
    contacts = $9, updated_at = $10
WHERE id = $1
`

type UpdateVendorParams struct {
	ID              uuid.UUID          `db:"id" json:"id"`
	Name            string             `db:"name" json:"name"`
	Type            ProviderType       `db:"type" json:"type"`
	CreditRating    string             `db:"credit_rating" json:"credit_rating"`
	PaymentDays     int32              `db:"payment_days" json:"payment_days"`
	PaymentCurrency string             `db:"payment_currency" json:"payment_currency"`
	PreferredVendor bool               `db:"preferred_vendor" json:"preferred_vendor"`
	Capabilities    json.RawMessage    `db:"capabilities" json:"capabilities"`
	Contacts        json.RawMessage    `db:"contacts" json:"contacts"`
	UpdatedAt       pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
}

func (q *Queries) UpdateVendor(ctx context.Context, arg UpdateVendorParams) error {
	_, err := q.db.Exec(ctx, updateVendor,
		arg.ID,
		arg.Name,
		arg.Type,
		arg.CreditRating,
		arg.PaymentDays,
		arg.PaymentCurrency,
		arg.PreferredVendor,
		arg.Capabilities,
		arg.Contacts,
		arg.UpdatedAt,
	)
	return err
}
